### ISSUE TITLE
Instantaneously display when a parameter is changed

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#10]
Definitively not a bug and not a priority, but ...
Could be interesting to make effort to refresh the display automatically when a parameter change occur.
One example, but there are others: after initialisation of pipeline, it is necessary to click on the node to refresh the parameters window.

**Comment by dhrbn** [comment]
https://github.com/populse/populse_mia/commit/8edb639446dbffe7973384b53b6d25caff3036f2 should close this (I let you test and close this issue if it is ok)

**Comment by dhrbn** [comment]
This issue has been closed by https://github.com/populse/populse_mia/commit/e4a668ac344d00b621c03c2ba5c6bd6f2da7827e

**Comment by servoz** [comment]
I reopening this issue, because there are other cases where it would be cool to refresh the display !
Thanks to your last improvement the outputs parameters are indeed refreshed after pipeline initialisation.
 But I just saw that it is not the case when, for example, after loading pipeline parameters.
I propose to leave open this issues and each time we observe one case where the  refreshment is not automatic, to report here

**Comment by servoz** [comment]
No refreshment with "load pipeline parameters" action

**Comment by servoz** [comment]
No refreshment after initialisation of pipeline -> fixed

**Comment by dhrbn** [comment]
Refreshment after "load pipeline parameters": done by https://github.com/populse/populse_mia/commit/72245b0caf98c99460f0227212f516836779bd0d

**Comment by servoz** [comment]
I am reopening this issue because it seems that it was closed 2 days ago, as a side effect of the rewrite of the history, which I made in order to delete from the history the large files now followed by git-fs.
The first investigation I conducted seems to indicate that following this operation, some issues have been closed (which I will reopen after some checks). The integrity of the populse_mia project does not seems to have changed (I think the SHA-1 of the commits were changed during the operations, that could explain the side effect observed!)
