### ISSUE TITLE
mia crashed during data export in the database

### ISSUE THREAD

**Issue by clemacq** [populse/populse_mia#100]
**Describe the bug**
MIA crashed when I try to import some nifti files (generated with dcm2nii) in the data browser.

**Generated error**
```
Data export duration in the database:
read_log time: 2.58 s


Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/home/clement/gitRepos/populse-mia/python/populse_mia/data_manager/data_loader.py", line 212, in run
    value = properties[0]
TypeError: 'float' object is not subscriptable
QObject::~QObject: Timers cannot be stopped from another thread

```

**To Reproduce**
1. Go to 'File->Import' in the data browser
2. Select the nifti files
3. Go to the 'Basket' tab
4. Click 'export to mia'
5. See the error

**Expected behavior**
Being able to load these nifti files

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Populse_MIA version 1.2.1

**Comment by clemacq** [comment]
Note:
I tried 2 different dicom->nifti converters: dcm2niix and mcverter.
The error only occurs when importing the data converted with dcm2niix.

**Comment by M40V** [comment]
I have the same error with dcm2niix, by adding a check in the data_loader to verify if _properties_ is a list, I no longer observe this error.
All scans are correctly loaded with their tags, I'll make a commit to close this issue once I finish testing on my station.
