### ISSUE TITLE
SPM Realign takes too much time to run in Python

### ISSUE THREAD

**Issue by BlancaNietoPetinal** [populse/populse_mia#101]
**Expected behavior**
Get the realigned images in 10-15 seconds, which is the time matlab takes to run the same function.

**Actual behavior**
The realign.run() takes 45-50 seconds to run.

**Additional information**
In case it is important, the code run is:
`realign = spm.Realign(jobtype = 'estimate')`
`realign.inputs.in_files = 'filename'`
`realign.quality = 0.9`
`realign.fwhm = 5.0`
`realign.separation = 4.0`
`realign.register_to_mean = True`
`realign.interp = 2`
`realign.wrap = [False, False, False]`
`realign.run()`

**Comment by M40V** [comment]
This may be an [explanation](https://github.com/neurospin/pypreprocess/issues/1) why the Realign is much slower in Nipype.

I run some Realign in Matlab, a Python console and Populse mia and I observe the same behavior. The Realign takes approximately the same amount of time with populse and the console while it is a lot quicker when using Matlab.

I'll look further in ways to use multithreading with nipype, but it might be better to ask directly the nipype team about this issue.

**Comment by M40V** [comment]
The single_comp_thread parameter is undefined for the default matlab command line in Nipype, it means that Matlab won't be restricted.
I used the pipeline engine of nipype to run a Realign on multiple processor, but it did not improve the speed of the process.
Finally I tried to use the [fix](https://github.com/dohmatob/pypreprocess/commit/da1d89dad44c91793e71d1f0b32a1d138cd54d1f) from neurospin/preprocesses to speed up Realign (code available below). I tried the fix with spm8 and spm12 but I get an error from the class that handles the Matlab command.

```
import re
import time 
from nipype.interfaces import spm
from nipype.interfaces.matlab import MatlabCommand
MatlabCommand.set_default_paths('/home/jibril/spm12')
MatlabCommand(mfile=False)
 
class _Realign(spm.Realign):
    def _make_matlab_command(self, contents, postscript=None):
        mscript = spm.Realign._make_matlab_command(self, contents, postscript=postscript)
        patched_mscript = re.sub("\.nii", ".nii,1", mscript)

def test_realign():
    # realign = spm.Realign(jobtype = 'estwrite')
    realign = _Realign(jobtype = 'estwrite')
    realign.inputs.in_files = '/home/jibril/.populse_projects/projects/bug_test42/data/raw_data/alej170316-IRM_Fonct._+_perfusion-2016-03-17_08-34-44-0-T1_3D_SENSE-T1TFE-00-04-25.000.nii'
    realign.quality = 0.9
    realign.fwhm = 5.0
    realign.separation = 4.0
    realign.register_to_mean = True
    realign.interp = 2
    realign.wrap = [False, False, False]
    start = time.time()
    realign.run()
    end = time.time()
    print(end-start)


test_realign()
```

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in test_realign
  File "/usr/local/lib/python3.5/dist-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python3.5/dist-packages/nipype/interfaces/spm/base.py", line 375, in _run_interface
    deepcopy(self._parse_inputs()))
  File "/usr/local/lib/python3.5/dist-packages/traits/trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'script' trait of a MatlabInputSpec instance must be a unicode string, but a value of None <class 'NoneType'> was specified.

**Comment by JanWP** [comment]
The single_comp_thread is indeed undefined. However, if not using the MCR (which is incompatible with this parameter), the inputs.single_comp_thread property of Matlab objects in NiPype is set to true by default. You can configure it for example by setting 
```
realign.mlab.inputs.single_comp_thread = False
```

In my testing, this did indeed affect the command line parameter, but not processing speed of the realign command. So in the end I agree that this does not seem to be the bottleneck.

**Comment by servoz** [comment]
This issue clearly does not come from populse but from nipype. Despite the fix in nipype on [26 October 2012] (https://github.com/dohmatob/pypreprocess/commit/da1d89dad44c91793e71d1f0b32a1d138cd54d1f), as suggested by M40V, the present ticket shows that this problem is not yet solved. If necessary, a new ticket should be opened at nipype. I'm closing this ticket, we can't do anything on our side (except to propose a PR to nipype ...)
