### ISSUE TITLE
Crash when importing BIDS dataset (link with #58)

### ISSUE THREAD

**Issue by clemacq** [populse/populse_mia#105]
**Describe the bug**
A crash occurred when exporting a BIDS dataset to MIA Data Browser

**Generated error**
```
Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/home/clement/gitRepos/populse-mia/python/populse_mia/data_manager/data_loader.py", line 290, in run
    value = datetime.strptime(value, format)
  File "/home/clement/Software/anaconda3/envs/populse-env/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/clement/Software/anaconda3/envs/populse-env/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data ' ' does not match format '%Y-%m-%d %H:%M:%S'
QObject::~QObject: Timers cannot be stopped from another thread

```

**To Reproduce**
1. Go to 'File->Import'
2. Click on 'BIDS'
3. Send data to Basket
4. Click on 'export to MIA'
5. See the error 

**Expected behavior**
Being able to export a BIDS dataset into MIA

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Populse_MIA version 1.2.1

**Comment by servoz** [comment]
Hey thanks to writing !

The BIDS data set is not yet handled in mia.
There is already a ticket (#58) on the need to implement it in mia. Your ticket is therefore a kind of duplicate of the first one. We keep both open, which will have to be closed at the same time.

As indicated in the first ticket (#58), we are only very few to work on the development of populse project and more specifically mia, which explains why this ticket is not get as a priority (we have other tickets with a much higher priority to process before this one). So, all good wills are welcome in the populse project and it is not necessary to hesitate to deal with the resolution of an issue.

The project is completely open (just make a git clone) and all contributions (pull requests) are received in a friendly way! Solving a problem is one of the ways to really enter the circle of populse developers!

**Comment by clemacq** [comment]
Hey, thank you for the answer! Sure, I understand your concern about the lack of workforce and ticket priority. 

However, I'm not sure this issue is a duplicate of #58 as my objective here is "only" to load a BIDS structured dataset into MIA (not to keep the BIDS structure inside the software). 

Olivier Montigon recently modified mri_conv to allow importing a BIDS dataset and as far as I understand the error, the problem is related to some format string mismatch between the import module (mri_conv) and the data browser. I'll try to help solving this issue!

**Comment by servoz** [comment]
Hey, thanks for writing again :smile: 
It will be a pleasure if you do a PR with a fix for this issue.
You're absolutely right, the two tickets are not exactly duplicates. Number 58 is more general and would solve the current issue.

**Comment by clemacq** [comment]
The error occurs when the CreationDate tag in the json has a value = " ". The datetime library generates an error trying to format this string into a pythonic time format.
Olivier just modified the way mri_conv assigns a value to the CreationDate tag when no information is provided (new value = ""). 
So this issue is closed!

**Comment by servoz** [comment]
So, as you said, this issue has nothing to do with the BIDS format after all? (just to know if I modify the link with issue 58 !!)

**Comment by clemacq** [comment]
The error occured when using the BIDS button in the importer (mri_conv). This button allows to import a BIDS structured dataset into MIA without preserving its structure. So closing the present issue does not close the #58.

**Comment by servoz** [comment]
That's not the point.
If I understood correctly, this ticket finally concerns a tag that was not compatible in mia.
isn't it?

**Comment by clemacq** [comment]
Yes, at the end, the error was generated by a tag format problem!

**Comment by servoz** [comment]
Thanks for your help !!!
