### ISSUE TITLE
nipype.interfaces.spm.preprocess.Realign does not initialize if it is not the first brick in a pipeline

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#106]
**Describe the bug**
When a pipeline contains an SPM Realign brick anywhere except at the first position, the names of the outputs of the Realign brick are not assigned. As a consequence, none of the inputs and outputs of the subsequent bricks are created as virtual entries in the database. The pipeline will run fine, and all the correct files will be produced in the data directory, but none of the non-initialized files will exist in the database. As a consequence, they cannot be used in MIA.

**Generated error**
None. However, MIA prints a message to the terminal during the initialization:
```
No output list method for the process realign1.
```

**To Reproduce**
1. In an empty pipeline manager window, place SPM smooth and realign bricks. Export the _in_files_ from smooth and the __mean_image_ from realign. Connect the __smoothed_files_ from smooth to the _in_files_ from realign.
2. Choose a 4D scan with at least two dynamic volumes as input to the pipeline, initialize the pipeline.
3. The message mentioned above appears in the terminal. The output file from smooth is correctly initialized, but the outputs of realign are not.
4. Run the pipeline. See the generated mean image file in the data directory. No corresponding entry exists in the database.

**Reason this happens**
According to discussions with @M40V et @servoz, this issues arises because the SPM Realign brick checks for the input file being not empty at the moment of initialization. This behavior is not compatible with our goal to initialize and check the pipeline before running it. 

**Expected behavior**
Ideally, the pipeline should initialize correctly and show all inputs and outputs to bricks before running. If a brick fails to initialize correctly, a warning to the user is expected, containing information about which brick fails to initialize and possibly an error message returned by the brick to help debug the problem.

If a pipeline runs correctly, it is expected that all generated scans show up in the database after the run. In this case, retrieving the info about the generated scans after the bricks run would at least render the realign brick usable, even if the possibility to debug pipelines and detect errors early is lost.

**Thoughts on how to solve**
- This specific case might be fixed by overloading the corresponding method. However, this will not prevent the very same issue from appearing again with other bricks. 
- If realign does not actually need to retrieve info about the input file (such as the number of dynamics) in order to function correctly, the check if the file is not empty may be considered over-zealous. In that case, an issue could be filed against nipype.
- If there are coding guidelines for bricks in nipype that state that the input file must exist at the moment of initialization of the brick, our model of initializing the entire pipeline before running it may need to be reviewed.

**Desktop**
 - OS: Ubuntu 18.04
 - Populse_MIA version: 1.1.1
 - nipype version: 1.2.0
 - mia_processes version: 1.2.1

**Comment by servoz** [comment]
Thank you very much @JanWP for this very detailed ticket, this will be a great help to find a solution!
This is not a simple stuff. To discuss.
High priority in the "Prioritisation of issues to be resolved" Milestone

**Comment by servoz** [comment]
This comes from the Nipype side. Nipype for Realign(), but maybe for other bricks, uses nibabel.load() in the Realign._list_outputs() method to check if the functional is a 3D. So there is a FileNotFoundError exception that is raised at initialisation time in mia because at that time the intermediate files are not yet created.
Unless we change completely the philosophy of mia to handle this case, why not?, we can think that opening a ticket about this at nipype would be more appropriate. 
I close this ticket, a new one can be opened later if nipype does not solve the problem.
