### ISSUE TITLE
The list of nipype bricks is unnecessarily cluttered

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#108]
**Expected behavior**
When a user installs and configures MIA, the computing environment is set up. In this environment, there may or may not be access to FSL, SPL, Brainvisa etc. A user might expect to have access in the pipeline manager only to the bricks that are actually available for use. A user might also expect to be able to quickly find a specific brick. Being able to fold unused interfaces to hide the list if individual bricks helps in reducing the list. A user might expect the folded interfaces to remain folded when MIA is closed and opened again.

**Actual behavior**
All interfaces present in nipype are shown with all of their bricks in a huge list of over 900 entries. The vast majority of these bricks shown can not actually be used in any given installation. This makes finding the right brick difficult. There is no search tool. When a user folds an interface, closes MIA and opens it again, that interface is shown unfolded again.

**Proposed improvements**
- Only interfaces corresponding to software present on a system should be shown. E.g. if SPM is not configured, the SPM bricks should not be shown. If FSL can not be found on the system path, the FSL bricks should not be shown, etc.
- There should be a simple search tool (accessible by Ctl-f or F3 or a search icon near the list).
- When a user folds interfaces to be hidden, and closes and re-opens MIA, that state should be restored, that is, these interfaces should remain folded.

**Comment by servoz** [comment]
Very nice enhancement proposal.
Can be a huge development work (with many ramifications, for example with the CapsulEngine which is still under construction...) ... Or not :-)
Currently, the simplest, and less elegant way than your proposal, is to use the package library manager (File>Package library manager) to select what the user wants to display in the package library. 
This does not make it possible to do everything you propose but it makes the package library display lighter!
Medium priority in the "Prioritisation of issues to be resolved" Milestone

**Comment by servoz** [comment]
Fixed in release 2
