### ISSUE TITLE
Provide method to easily delete user processes, linked with #71

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#111]
**Expected behavior**
When I save a pipeline, it automatically shows up in User_processes. Intuitively, I would expect to be able to delete it again by selecting it in User_processes and to hit the "Del" key on my keyboard. Preferably, a confirmation dialog would be shown before actually deleting it. The same functionality via right-click to bring up a context menu and selecting "delete" would be nice as well for mouse-centric users. As a last resort, the package library manager should allow me to remove individual bricks.

To be more specific of what I mean with deleting a saved pipeline, I mean removing the _User_processes/my_pipeline.py_ file and updating _User_processes/\_\_init.py___ and _process_config.yml_. 

**Actual behavior**
I am not aware of any method to delete that saved pipeline from within MIA. Instead, I need to remove the python file and edit the MIA config files and package init. The package library manager only allows to remove entire collections of bricks.

**Comment by servoz** [comment]
Sure ! We are currently working on this improvement! Coming soon ...

**Comment by servoz** [comment]
To close concomitantly with #71

**Comment by M40V** [comment]
I've [added](https://github.com/populse/populse_mia/tree/1ce04f2110959ca018edfa6068d055cc534f0114) a key event when the "Del" key is pressed while in developer mode in the pipeline manager tab.
Currently it allows to delete a package (delete the file from the disk), do we want to remove it instead (not show it in the TreeView) ?

**Comment by JanWP** [comment]
Confirmed to be working well here. Thanks!!

**Comment by M40V** [comment]
You can also use a right click now. We might want to add other action such as remove or hide package. I leave this issue open for discussion.

**Comment by JanWP** [comment]
Right click on a package or package library in the PM tab does not do anything on my machine in latest master. 

Indeed, if right-click brings up a context menu, a "hide package" option might be very useful, as going to _File-> Package library manager_ may not be the most intuitive place to look for inexperienced users.

**Comment by servoz** [comment]
Can you check that your are not in clinical mode (See File > MIA preferences in the Tools tab), please ?

**Comment by servoz** [comment]
Little reminder for close this ticket:
- in the Pipeline Manager:
    - Clinical mode:
        - Remove and Hide options available from right-click.
    - Developer mode:
        -  Remove, Hide and Delete options available from right-click.
- in the File > Package library manager:
    - Clinical mode:
         - Centre (or left justify) the Add and Remove button
    - Developer mode:
         - get possibility to reset a Delete action. The cancel button for close the window is effective to reset all actions (remove, add, hide or delete).
    - for developer and clinical modes:
         - Adding a brick only add that brick (and not all the bricks in the repository).

**Comment by JanWP** [comment]
Well spotted. I was indeed back in clinical mode, after juggling between different branches and not bringing back my original config files. Now I can see the _Delete_ and _Remove_ options on right-click.

Just to be sure I understand this correctly:
 - _Delete_ removes the entry from the tree and deletes the file
 - _Remove_ only removes the entry from the tree (\_\_init\_\_.py) but files remain 
 - _Hide_ leaves it in \_\_init\_\_.py, but sets it to _process_disabled_ in process_config.yml

Right?

**Comment by M40V** [comment]
- Remove leaves it in \_\_init__.py, but removes it in process_config.yml while file remain

**Comment by servoz** [comment]
After some thought, I think that the "hide" option with the right-click could be be very  time consuming in development for a little enhancement (this option is available in File > Package library manager; just 2 click !). I strike-through it above.

**Comment by M40V** [comment]
Currently the reset button does the opposite action of the option it was called from. It could cause some confusion.

For example in the package library manager, if we remove a package, then add this package, then reset the adding action, at the end we removed the package.
Do we want the reset action to restore package to their initial state or to just reverse the last action ?

**Comment by servoz** [comment]
I'm not sure I really understand and maybe I'm missing a subtlety.

If we remove A then add A and then reset the add of A, we expect to finally remove A, right?
So I think that the reset must correspond to the reset of the chosen action (moreover the user explicitly chooses the action to be cancelled, unless I am mistaken).

In my opinion, the return to the initial state (before the pipeline manager open) should only take place if the cancel button is clicked.
