### ISSUE TITLE
[general discussion] DataBrowser: right clic on a document and "Remove document(s)" only removes the corresponding entry in the database

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#112]
populse_mia.user_interface.data_browser.data_browser.TableDataBrowser.remove_scan()
This is very surprising at the first time, for example, when deleting a document in the Data Browser and then initialising a pipeline creating the same document name. Indeed in this case when returning to the Data Browser it is possible to observe the corresponding document in the miniViewer (normally the document is empty after only an initialisation)!!!!

In a first thought, we would like the real data to be deleted as well.

Is it really desirable in any case?

This also raises the Undo/Redo function problem. For the database Undo/Redo is supported fine. For real data, this would require the deposit of the real data in a temporary folder (with risks of error, name conflicts, etc....) and the deletion of the data at the end of use of mia... maybe not easy to do (maybe this is why the deletion of the real data is not currently done!).
To discuss ...

**Comment by servoz** [comment]
EDIT: The real data are deleted if "Remove document(s)" click was done, or if the document was created in an initialisation but not run, when exiting MIA. This is as a lesser evil, but the problem remains intact before exiting MIA.

**Comment by M40V** [comment]
- If we initialize then run a pipeline, it will create a document.
- If we remove this document then initialize the pipeline, we'll see the document in the data browser but it will not be empty, it'll be the results of the previous run.
- If we close MIA at this point, the document will be deleted, which is the expected behavior.
- If we run the pipeline again, the document will be updated accordingly to the last initialization.
- If we close MIA at this point, the document will not be deleted, which is the expected behavior.

During the initialization, if the output document already exist, we can ask the user if it should be erased or not or we can erase it without asking the user. What do you think ?

**Comment by servoz** [comment]
I'm supplementing your previous post:

- If we initialize a pipeline, it will create an empty file in the station and a document in the database.
- If we then run a pipeline, it will create a not empty file in the station and the document stay in the database.
- If we remove this document from the database (databrowser), and not from the station, then initialize the same pipeline, we'll see the document in the data browser but it will not be empty, it'll be the results of the previous run.
=> This exactly the purpose if this ticket !!! The management of the real data (in the station) at the same time of the document in the database (not the case now ...). In the first post:

> This also raises the Undo/Redo function problem. For the database Undo/Redo is supported fine. For real data, this would require the deposit of the real data in a temporary folder (with risks of error, name conflicts, etc....) and the deletion of the data at the end of use of mia... maybe not easy to do (maybe this is why the deletion of the real data is not currently done!).

 -etc. 

During the initialization, if the output document already exist, we can ask the user if it should be erased or not or we can erase it without asking the user. What do you think ?
I think this is a good idea to ask (very easy to code but it is possible that this gives side effects ... ) but the principal goal of this ticket is the real data management not only the documents in the databrowser !

**Comment by servoz** [comment]
After a private discussion with @LStruber, it was decided :
- When we delete a document from the database, the corresponding data is deleted from the hard disk as well.
- To do this properly we should:
  - In the warning pop-up
![Screenshot from 2022-01-04 14-21-13](https://user-images.githubusercontent.com/37933899/148066839-7adad4e7-c7ca-4a05-84d8-55c5661006be.png)
add the message: Be careful! this action is definitive (the data will be completely deleted and no "undo" will be possible afterwards): 
  - If the OK button is clicked:
    - delete the document from the database (already done).
    - delete the corresponding data from the hard disk (to do)

We should take the opportunity to clean up the undo / redo methods. A lot of work has already been done for the undo / redo lately. However it remains to look at what is done in the undo / redo and to specify in the docstring of the concerned methods. As it is already done in the populse_mia.user_interface.pipeline_manager.pipeline_manager_tab module:
![Screenshot from 2022-01-04 14-40-23](https://user-images.githubusercontent.com/37933899/148067635-f96dde3d-04c4-4524-8102-21296289c352.png)

It should also be decided once and for all, what is desirable to manage in the undo / redo. For now, things are not clear enough, e.g. it seems difficult to us to manage the undo / redo if we physically delete a data when we delete the document from the database (for the moment this case is managed by the undo / redo!).

Maybe it would be necessary to open another ticket for the specific question of the cleaning / clarification of the undo / redo ? I leave for the moment these ideas here, it will be always time to open a new ticket later.

**Comment by LStruber** [comment]
Proposed modifications were implemented.
Undo/Redo of "remove_document" action was commented, and undo/redoable possible actions has been added to the project.py docstring.
I suggest that another ticket should be open to deal with other concerns of undo/redo (clarification, cleaning)
