### ISSUE TITLE
MIA deletes data from one iteration of iterated pipeline when closing

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#117]
**Describe the bug**
When a pipeline is iterated and run correctly, all expected data are present. When MIA is closed and opened again, the data from the last iteration has disappeared.

**Generated error**
None

**To Reproduce**
1. Load any example data with two simple scans
2. Create a pipeline consisting of an _Input_Filter_ and a NiPype _smooth_ brick. Export input to database_scans, link _Input_Filter_ to _Smooth_, export output of _Smooth_.
3. Run the pipeline. Select any two scans. Note order of the iterations.
4. Go to the Data Browser, both smoothed scans are present. Optionally, save the project.
5. Close MIA, open it again, and load the project
6. One of the smoothed files is gone (for me, the last one, but not sure it is always the last).

**Expected behavior**
All data should remain in the project. Seems like an issue of over-zealous garbage collection.

**Desktop (please complete the following information):**
 - Ubuntu
 - Populse_MIA version: all up-to-date

**Comment by M40V** [comment]
I recently added a feature to clean on closing the initialized files that were not run. The last run of the iteration might be negated from this feature. I'll commit a fix quickly.

**Comment by JanWP** [comment]
Yes, from my preliminary testing, this seems to work. Still testing other pipelines, but for now it looks good. Thanks!
