### ISSUE TITLE
Do not display "false" bricks in the Pipeline Manager tab at startup.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#120]
Currently, some "false" bricks are displayed in the Pipeline Manager tab (ex. nipype.interfaces.spm.info). Last enhancements done allows to remove them by removing the package (ex. nipype) then adding again in the File > Package library manager but it would be very desirable that the job was done automatically at the first startup.

**Comment by M40V** [comment]
A naive solution might be to check if a (or multiple?) false brick is present in process_config.yml just after we check if nipype is installed with the correct version in the method _verify_processes_ of main.py.

If the user has already manually removed the 'false' brick, this fix won't be effective. Otherwise since this [commit](https://github.com/populse/populse_mia/commit/e68b00a3ba0f6c663b13637e3801b262cb11fcfb), the users that add nipype for the first time should not see "false" bricks.

**Comment by servoz** [comment]
Yes since this commit it is possible to manually (remove nipype then add again nipype in the File >  Package library manager) remove the fake bricks (I didn't test in all nipype sub-packages, but for the few that I tested it seems to do the job).

However, since several months, the normal functioning of mia is that the nipype and mia_processes libraries are directly and automatically managed at the start of mia (update, etc...). So I would find it a shame if the user have to remove and add nipype again by hand.

This is conceivable since it seems to give the expected result, but it would lack elegance (moreover in this case the user lose his whole configuration since all the bricks are enabled)! In addition, based on the commit you're talking about, I think it should be possible to do the job at startup (unless I'm mistaken, it would be enough to save the previous configuration in a temporary object - this is what happens when mia is launched, if a version of nipype or mia_proceses is updated - and to inject the old configuration after removing the fake bricks ?

If I remove the process_config.yml file, I guess mia is in a state very near of the first start of mia. In this case automatic process at the start of mia sets up the false bricks. We  have to, I think, apply the idea in your commit (which seems to do the job with the method that adds packages in the mia preferences), at start of mia (I think this is managed in the main module).

**Comment by servoz** [comment]
If the version of the packages embedded in mia have changed, automatic update at the start of mia overwrites the previous configuration. Before the last changes this configuration was kept (process_disabled or process_enabled) ...

**Comment by servoz** [comment]
After new tests, I think I was wrong and i apologize (it is possible that I had changed the configuration previously and without remembering ... it made me thinking that it was the update that produced the change).).
I close the ticket!

**Comment by servoz** [comment]
at last,  still a little detail to sort out !:
Please see below the result of:
- delete the process_config.yml file, make sure you have the last pipy version of nipype (pip3 install nipype --user; if no nipype was already installed in the station; this is the 1.2.2 version); Then launch mia. The automatic installation/upgrade at startup produce the first left column in process_config.yml (after a process configuration by the user that make disabled the mrtrix3 package).
- exit mia; make sure the very last github version of nipype is installed in the station (cd /tmp; git clone https://github.com/nipy/nipype.git; cd nipype; python3 setup.py install --user; if no nipype was already installed in the station; this is the 1.2.3-dev version); launch mia. The automatic installation/upgrade at startup produce the middle column in process_config.yml. In this, we see that the configuration is keept, except the new process/brick "MRResize" that is automaticaly made enabled. This is exactly what we wish.
- exit mia;  make sure you have the pipy version of nipype (pip3 install nipype --user; if no nipype was already installed in the station; this is the 1.2.2 version); Then launch mia. The automatic installation/upgrade at startup produce the right column in process_config.yml. In this case we know (from the 2 first steps), that the only difference between the two versions is the extra "MRResize" brick in the 1.2.3-dev version. So, we observe that in the right column, the "MRResize" brick is well removed (this is good), but all the bricks after are automatically made enabled (this no good). We don't want this, in this case we want just to back to the same state that the left column ...
![packageUpgrade](https://user-images.githubusercontent.com/37933899/65227650-50c6d380-dac9-11e9-8559-d22b75bfcb22.jpg)
