### ISSUE TITLE
Deal with bricks who expect to be provided the output file name (linked with #122)

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#121]
**Expected behavior**
There should be a builtin method in MIA to build output filenames for bricks who expect them as inputs.

**Actual behavior**
The CalcCoregAffine brick (maybe others as well) likes to be given the name of the output files as input. The __list_outputs_ method limits itself to passing the value of the input parameter to the output. If the input is not provided, at initialization the output file name remains empty, such that subsequent bricks in the pipeline do not have an input file name to work with and initialization fails. However, if this brick is the last in a pipeline, initialization does not fail and the brick can be run.

Since MIA does not currently provide a built-in mechanism of building file names based on user-defined rules (input files, iteration counters or values...), it is not straightforward to provide the input parameters this brick expects. Writing a simple custom brick building a suitable input file name could be a workaround here. I consider this solution clunky, since it adds clutter to pipelines, and to the _Bricks_ fields in the database entries of the output files produced.
Alternatively, since capsul does provide mechanisms for building such file names if I understand correctly, we may want to think about whether it would be useful and feasible to make these mechanisms accessible to users.

**Additional Context**
Here is the nipype code of that brick (```nipype/interfaces/spm/utils.py```, lines 67-129):
```python
class CalcCoregAffine(SPMCommand):
    """ Uses SPM (spm_coreg) to calculate the transform mapping
    moving to target. Saves Transform in mat (matlab binary file)
    Also saves inverse transform

    Examples
    --------

    >>> import nipype.interfaces.spm.utils as spmu
    >>> coreg = spmu.CalcCoregAffine(matlab_cmd='matlab-spm8')
    >>> coreg.inputs.target = 'structural.nii'
    >>> coreg.inputs.moving = 'functional.nii'
    >>> coreg.inputs.mat = 'func_to_struct.mat'
    >>> coreg.run() # doctest: +SKIP

    .. note::

     * the output file mat is saves as a matlab binary file
     * calculating the transforms does NOT change either input image
       it does not **move** the moving image, only calculates the transform
       that can be used to move it
    """

    input_spec = CalcCoregAffineInputSpec
    output_spec = CalcCoregAffineOutputSpec

    def _make_inv_file(self):
        """ makes filename to hold inverse transform if not specified"""
        invmat = fname_presuffix(self.inputs.mat, prefix='inverse_')
        return invmat

    def _make_mat_file(self):
        """ makes name for matfile if doesn exist"""
        pth, mv, _ = split_filename(self.inputs.moving)
        _, tgt, _ = split_filename(self.inputs.target)
        mat = os.path.join(pth, '%s_to_%s.mat' % (mv, tgt))
        return mat

    def _make_matlab_command(self, _):
        """checks for SPM, generates script"""
        if not isdefined(self.inputs.mat):
            self.inputs.mat = self._make_mat_file()
        if not isdefined(self.inputs.invmat):
            self.inputs.invmat = self._make_inv_file()
        script = """
        target = '%s';
        moving = '%s';
        targetv = spm_vol(target);
        movingv = spm_vol(moving);
        x = spm_coreg(targetv, movingv);
        M = spm_matrix(x);
        save('%s' , 'M' );
        M = inv(M);
        save('%s','M')
        """ % (self.inputs.target, self.inputs.moving, self.inputs.mat,
               self.inputs.invmat)
        return script

    def _list_outputs(self):
        outputs = self._outputs().get()
        outputs['mat'] = os.path.abspath(self.inputs.mat)
        outputs['invmat'] = os.path.abspath(self.inputs.invmat)
        return outputs

```

**Comment by servoz** [comment]
Of course, a built-in mechanism to build filenames based on user-defined rules is a very appealing idea and indeed in mia V2, capsul completion has been branched. However to answer this ticket exactly, my feeling is that a "general"" completion will never be as precise as the one that can be implemented in a given brick (process).
The nipype bricks are provided "as they are" and my experience is that in some cases they contain either real bugs or a philosophy that is not adapted to the mia one.
Moreover, in the case of pure nipype bricks, mia loses a part of its originality, which is the link with the database (no tag heritage! no automatic request ! etc. ).
So, I strongly advise to overload nipype bricks in mia_processes, for all these reasons (I don't develop also the interest for the community to propose in mia_processes bricks without any bugs and perfectly adapted to mia ...).
Moreover, it fix this issue ...
