### ISSUE TITLE
pipeline_manager_tab does not update itself correctly when a brick is removed from a pipeline  (Linked with #137)

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#123]
**Describe the bug**
If the initialization of a brick fails and if that brick is then removed from the pipeline, MIA crashes during the initialization of the new (smaller) pipeline because the removed brick is somehow expected to be found. 

**Generated error**
```
Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/home/warnking/code/fmri_processing/python/populse_mia_2019/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1087, in initialize
    self.init_pipeline()
  File "/home/warnking/code/fmri_processing/python/populse_mia_2019/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1013, in init_pipeline
    pipeline.nodes[node_controller_node_name].process,
KeyError: 'smooth2'
```

**To Reproduce**
1. In an empty pipeline window, place two SPM _smooth_ bricks. 
2. Export the mandatory _in_files_ plug of the first brick, and the non-mandatory _fwhm_ plug of the second. Do not export or connect the mandatory _in_files_ plug of the second _Smooth_ brick. Export the __smoothed_files_ output plugs the second brick. [Optionally, export the output of the first brick to a different name. Optionally, connect the _fwhm_ plug of the first smooth brick to the corresponding input parameter].  
![image](https://user-images.githubusercontent.com/11682353/64775787-3637ac00-d557-11e9-996f-53bdf79c9f46.png)
3. Set values for the exported input parameters.
4. Initialize the pipeline. Initialization fails (```No output list method for the process smooth2.```).
5. Delete the second _Smooth_ brick. If the output of the first brick was not connected, connect its output to the now empty output plug, or export it to a different name. Optionally, remove the unused _fwhm_ input plug.
![image](https://user-images.githubusercontent.com/11682353/64775900-79921a80-d557-11e9-82de-c45c66f56522.png)
6. Initialize the pipeline again. MIA crashes.

**Expected behavior**
The second pipeline, after removal of the smooth2 brick, is valid, and it should initialize correctly.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Populse_MIA version: Master as of today

**Comment by JanWP** [comment]
The problem is, the node controller is never informed of the deletion of the brick. This should probably be done by the _del_node_ method of the PipelineEditor. I'm still trying to figure out, what the correct way is to trigger that update.

**Comment by M40V** [comment]
The update is triggered by a QtCore.pyqtSignal when the node is clicked, it launches the displayNodeParameters method from pipeline_manager_tab.py.
Clicking on any other brick allows us to avoid the bug, so I'll try to reproduce this behavior after each deletion of a node.
