### ISSUE TITLE
MIA crash when initialising a brick from the mia_processes brick library, if the input parameters are not defined.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#124]
This is just to keep in mind this issue for fix it later because I didn't work on it at all (I don't really know if the problem comes from the input parameters as it is written in the title ...)

2 examples :

1/
  - open mia
  - go to Pipeline Manager
  - take the smooth brick (in mia_processes - preprocess - spm)
  - click on the button: Pipeline - Initialize pipeline
-> no problem observed

2/
  - open mia
  - go to Pipeline Manager
  - take the smooth brick (in mia_processes - preprocess - spm)
  - right click on the brick, then choose "Export unconnected mandatory plugs"
  - click on the button: Pipeline - initialize pipeline
-> Mia crashes with this exception:

```
Traceback (most recent call last):
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1411, in initialize
    self.init_pipeline() # When clicking on the Pipeline > Initialize
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1091, in init_pipeline
    BRICK_INPUTS, inputs)
  File "/home/econdami/.local/lib/python3.6/site-packages/populse_db-1.1.1-py3.6.egg/populse_db/database.py", line 1001, in set_value
    new_column = self.__python_to_column(field_row.type, new_value)
  File "/home/econdami/.local/lib/python3.6/site-packages/populse_db-1.1.1-py3.6.egg/populse_db/database.py", line 1639, in __python_to_column
    return json.dumps(value)
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type '_Undefined' is not JSON serializable

```
If we do the same thing (the 2 examples) with the smooth brick from the nipype library, it works fine....

**Comment by denisri** [comment]
Traits often use `Undefined` as default values, so we get these values in parameters (filenames especially) when some of them are missing. `Undefined` is not serializable in json by default. There are (at least) three ways to overcome this problem:
* avoid Undefined values and ensure we use None as default in every trait definition, but this is very difficult to ensure in toolboxes out of our control (and possibly nipype processes?)
* save json using a custom encoder, and load using a custom decoder. Those would not be regular json files (or would need interpretation for some values). If I understantd this is inside populse_db so we are "allowed" to use a non-standard json here I guess.
* don't use json but a different format to save process parameters values. For instance, Yaml manages this by saving a code defining the object type (python module/class). For instance an Undefined value is saved as `!!python/object/apply:traits.trait_base._Undefined []`, and correctly reloaded Probably the easiest choice.

**Comment by servoz** [comment]
What you're saying makes a lot of sense.
And spontaneously, I will also try the third solution first!

There is just one thing that surprises me (but since I haven't looked seriously at this issue at all, chances are I'm missing something obvious!), it's that with a Smooth brick coming from nipype, there's also an default value of the traits to Undefined and with this brick the initialisation doesn't crash  ...

**Comment by denisri** [comment]
Yes nipype processes also have Undefined values, and it's not clear why they don't cause the same  problem. Anyway thie problem exists and should be addressed.

Is the json format in any way builtin or mandatory in populse_db ? (I mean, some database implementations such as PosgresQL could be aware of it and interpret/optimize json ?)

**Comment by sapetnioc** [comment]
The data structure of populse_db is restricted (with less freedom than
JSON) because it must be serializable in SQlite (that does not support
JSON). Moreover, data must be interpreted by populse_db when processing
queries. It is not impossible to introduce a change in supported data types
but this will require to decide how to serialize the new structure in a
table and how this structure would affect the query language. Then some
code modification will be necessary.

Le mar. 8 oct. 2019 à 14:56, Denis Rivière <notifications@github.com> a
écrit :

**Comment by denisri** [comment]
1. Do we have a choice about supporting the `Undefined` object ? As we have seen traits make an insentive use of it, and nipype consequently does (just as capsul). We could work (quite hard) to eliminate `Undefined` from *our* processes and pipelines, but they would still be here in nipype processes. So I guess supporting it is just mandatory ?
2. How entangled is the JSON format in populse_db ? As Yann says it's not supported by SQLite, I understand it is used as a serialization format to store data in a SQL database. Would any other serialization work as well (YAML would thus be a good candidate, unless it has performance issues compared to Json) ? Or is JSON used directly in some database implementations ? Or used as an exposition format (in queries...?)
3. What would be the needed modifications in queries to support `Undefined` ?

**Comment by sapetnioc** [comment]
For populse_db, YAML will  not help because JSON is not used for
serialization. Instead we have our own code to transform data and queries
into SQL. So we must firs decide how to put an undefined value in database
(not so easy because, for instance, a date column can only contain valid
dates or NULL). And then decide what to do with queries and undefined. I
have the feeling that an important question is to know the difference
between None and undefined. If we need both in populse_db, it may be a bit
complicated.

But it may be possible to keep populse_db untouched and to change the way
pipelines values are serialzed/deserialized in it by adding some
meta-information in a pre-populse_db serialization step and use this
meta-info in a post-populse_db deserialization step. I am not sure this is
the right way to go but it is worth considering.

**Comment by servoz** [comment]
Yes, for nowI think it is possible to keep populse_db intact....

Indeed, when I opened this ticket, I was busy with other codes and I mainly wanted to write down what I observed so I wouldn't forget and fix it later.

I just looked, and the problem came from a change I had made...
In fact populse_db doesn't like the value traits.api.Undefined at all, that's why we do (in populse_mia.user_interface.pipeline_manager.pipeline_manager_tab) this hack:
```
if inputs[key] is Undefined:
    inputs[key] = "<undefined>"
```
Now I recently made an unfortunate change to make it active only for nipype processes...

I corrected and I close this ticket, sorry !
