### ISSUE TITLE
Issue in File > Mia preferences > Pipeline (mia preference)

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#128]
* Minimum steps to reproduce:

    If the entries spm_standalone and matlab_standalone do not exist in the config.yml file (in case of a new populse_mia installation):

    - in the mia preferences (File > Mia Preferences) and Pipeline tab (Config Matlab and SPM), check the Use Matlab standalone button and give the Matlab standalone path, then check Use SPM standalone button and give the SPM standalone path, then click the OK button. The test configuration does not generate an error but only the spm_standalone path is created in the config.yml file, the use_matlab standalone path (it might be very desirable to change this entry with use_matlab_standalone) remains false and the matlab_standalone path is not created in the config.yml file, so the configuration is wrong !

The workaround solution consists in unchecking Use SPM standalone, checking Use Matlab standalone only and then defining the Matlab standalone path.... it most certainly indicates a coding error !

**Comment by servoz** [comment]
I think it should be very important to play (tests) a little bit with the File > Mia Preferences > Pipeline part.
I just see that if nothing is declared yet (fresh installation case):
- check the Use Matlab box, then give the Matlab path, then,
- Check the Use Matlab in standalone mode box, then give the Matlab path in standalone mode, then click the Ok button, then
- open again File  > Mia Preferences > Pipeline ... The Matlab path has not been saved...

**Comment by servoz** [comment]
8dd2d19 only corrects the first case (first post) of this ticket.
In the second post, I think it was more a general question about how to make a total configuration (beyond the chosen configuration by checking the boxes).
8dd2d19 does not solve the problem expressed in the second case.

**Comment by M40V** [comment]
Right now we execute a test to verify the configuration when the corresponding checkbox is checked, if the test works, the input path is saved in the configuration file.
Instead launching the test as long as there's characters in the input field even if the checkbox is not checked will solve the second case but it might raise other problems.

**Comment by servoz** [comment]
Okay for the current code status (first sentence).
But for the resolution of this ticket?
I guess, instinctively an user will define the whole configuration at the first startup, not just the one he is supposed to use in the first pipeline he will use? 
Can you develop the second sentence, especially for the problem that could be observed?
