### ISSUE TITLE
The password to switch to admin mode is useless

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#129]
The current hack to become an administrator without using the protection password is:
1- get out of mia.
2- edit the config.yml file
3- you want to be a user? : user_mode : true
4- you want to be an administrator? user_mode : false
5- launch again mia ....You can be whoever you want to be

**Comment by M40V** [comment]
The config file is now encrypted, users should not be able to edit this file easily anymore.

**Comment by servoz** [comment]
Ok that looks better !
