### ISSUE TITLE
In admin mode it is not possible to overwrite an existing project

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#131]
Let's say that the Test00 project is known to mia.
File > Saved projects: choose Test00
File > Save project as: in Name field, let's say test2 is entered.
File > Saved projects: choose Test00
File > Save project as: in Name field, test2 is entered.
Even in admin mode, it is not possible to use the Save as button (or more precisely, the "Save as" button only allows to enter the test2 directory).

**Comment by servoz** [comment]
With cb4aac4 it seems it is possible to overide an existing projetc. But how do you create a new one ?

**Comment by M40V** [comment]
The directory mode of QFileDialog allows us to overwrite existing directory but remove the option to create a new one which defeats the purpose of the "save as" action. I haven't found another way to overwrite files directly with QFileDialog.
We can allow the right click in the pop-up for admin user, then they'll be able to delete manually a project from the window.
I'll reverse the commit https://github.com/populse/populse_mia/commit/cb4aac4e5fa24ef1b02f3674cbb0b9a1ae9eb7d3, but I'll keep the right click disabled at least for the non-admin user for now as we don't want them to mess with project files.

**Comment by servoz** [comment]
I think the change is not good. If we want to overwrite the test2 (first post), we go in test2 and finally it is the possibility to create test2 in test2.
I do not understand the right click in the pop-up and delete manually a project from the window.

**Comment by servoz** [comment]
This ticket is now almost fixed. Just to remind that we still have to correct the fact that we have to click twice on the yes button of the QMessageBox "populse_mia - Warning: Overwriting project".

**Comment by servoz** [comment]
With e2e7f94, it looks like this ticket can be closed.
