### ISSUE TITLE
Not appropriate warning if we decide to stop the "save project as"

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#132]
To reproduce:
File > Save project as, then you decide to do nothing, click on cancel:
Warning: This name already exists in this parent folder

**Comment by servoz** [comment]
It may be a question of detail, but the field to name the new project directory is File_name, which is inappropriate and can be confusing and the file of type field is useless.

**Comment by M40V** [comment]
If I do nothing, the warning doesn't appear on my station, but it does if I click on a directory then click on cancel.

**Comment by servoz** [comment]
Fine ! I close this issue.
