### ISSUE TITLE
Rewind after initialization deletes the data if the process changes the input data (ex. estimate parameter with realignment)

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#135]
Minimum step to reproduce:
Let's say we have a project called "test" with an anat and a func in the database. 
- drag and drop a mia_processes.preprocess.realign brick in the Pipeline Manager
- Right-click on the brick and choose "Export all unconnected plugs".
- Click on the Inputs node and then on the Filter button corresponding to the in_files parameter (Controller, on the right of the Pipeline Manager tab)
- Select the func data.
- Click Pipeline > Initialize pipeline.
- Then exit Mia.
- Restart Mia.
- File > Saved projects and choose test
The test project now has only the anat...... This is a significant risk of data loss!

This is a simple case to reproduce, but there are other ways to lose data. For example, without outputting and reopening mia, by initialising with jobtype == estimation, then with a second initialisation with jobtype == write ...

**Comment by M40V** [comment]
I've added a check so that output that are also input files are not removed. When the #25 issue will be solved, this check might no longer be necessary as input files and output files will be in different directories.

**Comment by servoz** [comment]
Great, this fix already seems to be working. I think this ticket can be closed! Hooray
