### ISSUE TITLE
Python file starting with #

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_mia#136]
There are two Python files starting with the `#` character in `popuse_mia` module directory.

**Comment by servoz** [comment]
and ?

**Comment by sapetnioc** [comment]
Well, on first sight it seems to be a mistake because :

```
from populse_mia import #install_mia                                                                                                           
  File "<ipython-input-1-884c006b9cc5>", line 1
    from populse_mia import #install_mia
                                        ^
SyntaxError: invalid syntax
```

**Comment by sapetnioc** [comment]
This is the kind of comments that makes me hesitate to create an issue because it does not make the program fail. But seeing this kind of file names immediately raises attention of people used to see Python codes. It may become important later if we want a community of developers around our tools. I just want to catch attention to things that troubles me but this kind of issue may be closed without changing the code.

**Comment by M40V** [comment]
These are files that were used by the software at some point but not currently. Some bits of the code might still be useful in the future so we were reluctant to remove them completely from the project.
The #image_viewer module is also fully commented.

**Comment by servoz** [comment]
the # module will be deleted when we no longer need it (but if it is really disturbing, I can delete them from the Github project after saving them at home). can I close this ticket?

**Comment by sapetnioc** [comment]
It is not urgent at all.
