### ISSUE TITLE
mia may crash during initialization because the controller has not been updated automatically. (Linked with #123)

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#137]
Minimum steps to reproduce:
- open mia
- go to the Pipeline Manager tab.
- drag and drop the mia_processes Smooth brick
- click on the brick: this initialises the Controller with the default values of the parameters and the name of this node (e. g. smooth1, here)
- click Pipeline > Initialize Pipeline. (this step can be omitted)

Then you decide to work with the Realign brick instead:
- Right-click on the Smooth brick and choose Delete Node
- Drag and drop the Realign brick
- Then, do not click on the brick (to keep the node at smooth1 in the controller) and click Pipeline > Initialize pipeline.
- mia crash

```
Traceback (last call to date):
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_manager_tab.py", line 1208, in initialization
    self.init_pipeline() # When you click on the Pipeline > Initialize button
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1074, init_pipeline
    pipeline.nodes[node_controller_node_name].process,
KeyError:'smooth1' (smooth1)
```

Ok, the user doesn't normally have to initialise a node with the unconnected input and output nodes AND normally it's better to tell the controller which pipeline we're working on, BUT it's a possibility of a crash and there's no doubt that a user will do it one day ! 

Without having taken the time to check, this ticket may join another one about the controller's automatic update.

**Comment by M40V** [comment]
i think it might be linked with the #123 issue, it's also the fact of not updating the controller after deleting a node that causes a crash.
