### ISSUE TITLE
The initialisation test is too permissive (linked with #143)

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#142]
Initialising a pipeline in one Pipeline Manager tab with success permit to run the pipelines in all tabs !

Example:
- Launch Mia
- Import or open a project with for ex. one anat.nii
- Go to Pipeline Manager
- In the New Pipeline tab, drag and drop the Smooth  brick from the mia_processes library
- Open a new tab then drag and drop for example a NewSegment brick from the mia_processes library
- On this NewSegment brick, right click and choose Export all unconnected plugs
- Go to the first tab then, on the smooth brick, right click and choose Export all unconnected plugs
- Click on the inputs node then click on the Filter button for the in_files parameter, in the controller (right part of the window).
- Select the anat.nii file from the database.
- Pipeline > Initialize pipeline
- Go to the tab with the NewSegment brick and run this brick, that was not initialised !

**Comment by servoz** [comment]
I've just tested the first post and the problem doesn't seem to be fixed.

**Comment by servoz** [comment]
It's not working properly !!!
For the first post, the last sentence is now:
- Go to the tab with the NewSegment brick: the "run" button is disabled (exactly what we wanted!)
BUT :
if we go back to the tab with the smooth brick that was previously initialised, the "run" button remains disabled !

OK, this current operation is like forcing the user to run the calculation just after initialisation (if he change of tab, it is necessary to do again the initialisation for all the tabs). It is already better than which existed previously, but it is a little bit hardcore

**Comment by M40V** [comment]
Ok, I didn't understand we wanted this feature. In this case I propose we link this issue to #143 in which it'll be interesting to reactivate the run button if after some changes the node parameters are put back to the ones used for initialization.
After an initialization we'll store in a variable the index of the tab (update this index if tabs are closed) and the parameters. If they change, the run button will be disabled, if they're restored to their previous value, it will be enabled again.

**Comment by servoz** [comment]
Indeed, linking this ticket with #143 makes sense.

**Comment by servoz** [comment]
So, I think linking tickets #142 and #143 together is like saying:
- Each tab has its own initialised "mode" or not. So, if a tab is successfully initialised (run button active), if we change tab, we'll be in the initialised mode of this new tab (if this tab has been successfully initialized before, the run is available and if not, it's disable).
- In a tab, if a pipeline has been successfully initialised, if a parameter of this pipeline is changed, it is necessary to initialise it again. The best  would be if the tab has a memory of the initialisation results for each set of parameters already used during previous initialisation (it's not too complicated using a dictionary I think, but it requires a bit more coding ... but it would be much better).

**Comment by servoz** [comment]
A test was performed in #143 that seems to indicate that this issue is now fixed.

**Comment by servoz** [comment]
As we discussed with @M40V this afternoon, we did not sufficiently consider the interaction with the database for the implementation of the management of successive initialisations. I reopen this ticket, because we will now have to improve the database management in the case of several successive initialisations without running the calculation. 

Steps to reproduce:
- Launch Mia
- Import or open a project with for ex. one anat.nii and one func.nii
- Go to Pipeline Manager
- In the New Pipeline tab, drag and drop the Realign and Coregister bricks from the mia_processes library
- Right click on the Realign brick and choose Export all unconnected inputs
- link the realigned_files and mean_image plugs of the Realign bricks to the apply_to_files and source plugs of the Coregister brick,  respectively
- Right click on the Realign brick and choose Export all unconnected outputs
- Right click on the Coregister brick and choose Export all unconnected outputs
- Right click on the target plug of the Coregister brick and choose Export plug, click on ok
- Click on the inputs node then click on the Filter button for the in_files and target parameters, in the controller (right part of the window).
- Select the func.nii and the anat.nii files, respectively,  from the database.
- Pipeline > Initialize pipeline
- Go to Data Browser and observe the result (all is good)
- Open a new tab then drag and drop for example two Smooth bricks from the mia_processes library
- Right click on the smooth1 brick and choose Export all unconnected inputs
- Right click on the smooth2 brick and choose Export all unconnected outputs
- Link the smoothed_files of the smooth1 bricks to the in_files of the smooth2 brick
- Click on the inputs node then click on the Filter button for the in_files parameter, in the controller (right part of the window).
=> First issue, with have now only access to the anat.nii scan !
- Select the anat.nii file from the database.
- Pipeline > Initialize pipeline
- Go to Data Browser and observe the result (all is good, but we have lost the outputs for the first tab. => Second issue, vide supra. In fact, in our current way of working, it is useless to manage the successive initialisations because the database is only ready for the last pipeline initialised ...)
- Go back to the fisrt tab.
- Pipeline > Run pipeline
- Mia doesn't crash, but the pipeline isn't launched. There's this message in the terminal:
The document with the name cdef024a-f3d4-495b-8846-966df7d725aa does not exist in the collection brick  => Second issue
- third issue (less important, but annoying): We observe in the message bar of mia: Pipeline "" has been correctly run => this is a fake news !

**Comment by M40V** [comment]
As discussed with @servoz, the commit cf41061 limit the run pipeline action to the last initialized pipeline. If there's multiple tabs opened, the run action will be enabled only when on the tab that was initialized last. It allows us to avoid the issues with the database management stated in the previous post.
