### ISSUE TITLE
The outputs of the realign brick seem to lose their history of passage through this brick when another brick follows it.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#144]
Example:

Run a Realign brick with jobtype=estwrite and write_which=[2,1] (default brick in mia_processes).

We find in DataBrowser:
- Func.nii: Realign1
- rFunc.nii: Realign1
- meanFunc.nii: Realign1
- rp_Func.nii: Realign1
=> OK !

Run a pipeline consisting of a Realign brick (same as before) then a Coregister brick with jobtype=estimate  (default brick in mia_processes) and target=Anat.nii, source=the meanFunc.nii coming from the realign brick, apply_to_files=rFunc.nii coming from the realign brick.

We find in DataBrowser:
- Func.nii: No brick history
- rFunc.nii: Coregister1
- meanFunc.nii: Coregister1
- rp_Func.nii: No brick history

It's not a bug that crashes mia but it's a loss of important informations. So it's not a priority issue but we have to keep it in mind to fix it as soon as possible.

**Comment by M40V** [comment]
The commit https://github.com/populse/populse_mia/commit/55b5b091133f63d2ef015dac03231b333da6a554 should solve this issue but I sometimes get a Segmentation fault when changing parameters value.

**Comment by M40V** [comment]
I observed the same issue with mia_processes but there is no problem with nipype bricks. 

After the initialization the informations are present, they disappear after running the pipeline.
The RunPipeline method and theses mia_processes bricks shouldn't be able to modify the databrowser brick history.

**Comment by servoz** [comment]
Um, not sure...
At runtime, we update the Exec and Exec Time tags in the COLLECTION_BRICK, if I remember correctly.

**Comment by M40V** [comment]
Yes, so it must come from process_mia.py.

**Comment by servoz** [comment]
No time to see it now (there is still enough bug to fix before this improvement) ... I'll see it when I'll have a couple of hours in front of me ...

**Comment by servoz** [comment]
it seems that this issue no longer exists in V2. I close this ticket
