### ISSUE TITLE
mia crash due to not resetting the controller when we close a tab in the Pipeline Manager

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#145]
As an example:
- Launch Mia
- Go to Pipeline Manager
-  In the New Pipeline tab, drag and drop the Normalize12 brick from the mia_processes library
- Click on this Normalize12 brick, this will update the controller with the default parameters for this brick
- Close the tab (click on Do not save)
- Drag and drop the Realign brick from the mia_processes library
- Click on Initialize pipeline
- mia crash

A working around solution could be to reseting the controller when we close a tab (as when we do do right click then Delete Node on a brick)

**Comment by M40V** [comment]
I think we might have the same type of crash when we change tabs before initializing, so I'll reset the controller after a tab change too before closing this issue.
