### ISSUE TITLE
Make mia compatible with populse_db v2

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_mia#146]
In populse_db v2 the API has changed slightly but the internal implementation is completely different. But in `populse_mia.data_manager.database_mia` there are two classes (`DatabaseMIA` and `DatabaseSessionMIA`) that  redefine some populse_db base methods. These methods are completely re-implemented  and are therefore incompatible with internal changes in populse_db v2. The goal of this redefinitions is to add the following Mia custom attributes to populse_db fields: `visibility`, `origin`, `unit` and `default_value`.

To fix this issue, it is better to remove all code from MIA that replaces internal populse_db methods. There are two options :
1. Modify mainly populse_db API to add the possibility to define custom attributes on fields.
1. Modify mia to use actual populse_db API to store the custom field attributes. For instance these custom attributes could be stored in the fields of a `mia_field_attributes` collection.

**Comment by sapetnioc** [comment]
I started to try to change mia and populse_db 2.0 to solve this issue. There is a mia branch `populse_db_2` that is supposed to work with populse_db branch `2.0`. So far I have been able to import two NIFTI files but since I do not know mia very well, I would like someone else to test these branches and tell me the recipe to reproduce a problem that should not happen.

**Comment by servoz** [comment]
Ok, I'll look at it next Monday.

**Comment by servoz** [comment]
1/ Old data (processed with old versions of populse_db and populse_mia) do not work anymore. It's not a big deal because I think we don't have real users yet :-)
```
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/main_window.py", line 594, in open_recent_project
    self.switch_project(relative_path, name)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/main_window.py", line 978, in switch_project
    self.update_project(file_path)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/main_window.py", line 1121, in update_project
    self.pipeline_manager.update_project(self.project)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1767, in update_project
    self.project.session.get_shown_tags()
  File "/data/Git_Projects/populse_mia/python/populse_mia/data_manager/database_mia.py", line 175, in get_shown_tags
    for i in self.filter_documents(FIELD_ATTRIBUTES_COLLECTION, '{visibility} == true'):
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_db-2.0.0-py3.7.egg/populse_db/database.py", line 767, in filter_documents
    raise ValueError("The collection {0} does not exist".format(collection))
ValueError: The collection mia_field_attributes does not exist
```

2/ With newly imported data with new versions of populse_mia and populse_db it seems to work fine.
I'm going to play a little bit and indicate below the problem encounters:

**Comment by servoz** [comment]
1. The Controller Filter is not working properly:
    - Minimum steps to reproduce:
        - open Mia
        - File > Import
        - as usual select images to convert. Let's say an 3D anatomical image. Export to Mia
        - go to Pipeline Manager tab
        - drag and drop the smooth brick from the mia_processes library
        - right click on the brick then choose "Export all unconnected plugs"
        - click on the brick to make available the Filter buttons in the controller (right part of the Pipeline Manager tab)
        - click on a filter button: mia crash:
```
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/node_controller.py", line 388, in display_filter
    node_name, plug_name, self, self.main_window)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/node_controller.py", line 861, in __init__
    self.advanced_search.show_search()
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/advanced_search.py", line 646, in show_search
    self.add_search_bar()
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/advanced_search.py", line 177, in add_search_bar
    self.displayConditionRules(field_choice, condition_choice)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/advanced_search.py", line 288, in displayConditionRules
    if (tag_row is not None and tag_row.type in no_operators_tags) or \
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_db-2.0.0-py3.7.egg/populse_db/database.py", line 68, in __getattr__
    raise AttributeError(repr(name))
AttributeError: 'type'

```
A rapid introspection shows that the  tag_row object in the displayConditionRules() method of the AdvancedSearch() class in the populse_mia.user_interface.data_browser.advanced_search module do not have the type attribute ...

with populse_db  remotes/origin/2.0 and populse_mia remotes/origin/populse_db_2:
`dir(tag_row):  ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_append_key', '_delete_key', '_dict', '_items', '_key_indices', '_values', 'default_value', 'origin', 'unit', 'visibility']`

with populse_db master and populse_mia master:
`dir(tag_row):  ['__abstract__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__mapper__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__table__', '__weakref__', '_decl_class_registry', '_sa_class_manager', '_sa_decl_prepare', '_sa_instance_state', '_sa_raise_deferred_config', 'classes', 'collection_name', 'default_value', 'description', 'field_name', 'metadata', 'origin', 'prepare', 'type', 'unit', 'visibility']`

**Comment by servoz** [comment]
2. The add tag feature is not working properly:
    - Minimum steps to reproduce:
        - open Mia
        - File > Import
        - as usual select images to convert. Let's say an 3D anatomical image. Export to Mia
        - in Data Browser, click in Tags > Add tag
        - in Tag name field types "Patient", click on
        - mia crashs:

```
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pop_ups.py", line 551, in ok_action
    self.new_tag_unit)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 186, in add_tag_infos
    new_tag_name, table_to_database(new_default_value, tag_type))
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_db-2.0.0-py3.7.egg/populse_db/database.py", line 625, in add_value
    if self.engine.get_value(collection, document_id, field) is not None:
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_db-2.0.0-py3.7.egg/populse_db/engine/sqlite.py", line 505, in get_value
    self.cursor.execute(sql, [document_id])
sqlite3.OperationalError: no such column: FileName
```

**Comment by servoz** [comment]
3. It does not appear to be possible to suppress the tag view in the data browser:
    - Minimum steps to reproduce : 
        - open Mia
        - File > Import
       - As usual, select the images to be converted. Let's say a 3D anatomical image. Export to Mia
       - in the data browser, click on the "Visualized tags" button
       - Highlight the first 5 lines (1st affine transformation line, 2nd affine transformation line, 3rd affine transformation line, AcquisitionDate, AcquisitionTime)
      - click on the right pointing arrow
      - click on OK
      - these 5 tags are now also displayed in the Data Browser
      - in the data browser, click on the "Visualized tags" button
      - Highlight the 5 tags that were previously selected
      - click in the left pointing arrow
     - the 5 tags remain displayed in the Data Browser
No exception is raised!

**Comment by servoz** [comment]
4. It's hard to do a serious speed test, as there doesn't seem to be much that works in mia with the populse_db V2, but the feeling I have is that it doesn't seem to go much faster with the new version! To be checked later when it will work better.

**Comment by denisri** [comment]
I could make the main functionalities to work using populse_db 2 (import, filter/select pipeline parameters from the database, run), incluiding some performance issues fixes, but many tests are still failing. I didn't go very deep in this part but I'm not very experienced with this part and I quite struggle to understand why there are behaviour differences between populse_db 1 and populse_db 2.
I have converted the test database `resources/mia/project_8/database/mia.db` somewhat manually to populse_db v2, and so far I can't tell if I have failed to convert something in it, or if some things are actually going wrong with this new populse_db. As it's beginning to take me too much time, I'd appreciate a little bit of help on that.
There are 2 branches that can be used to test:
- `populse_db_2`: from current `master`, changes for using populse_db 2 API
- `populse_db2_capsulengine`: merges both `capsulengine` and `populse_db_2` branches.

**Comment by sapetnioc** [comment]
I did not know that a database was stored for the tests. The database internal structure is completely different (column names changed and drop SQLAlchemy layer). To make the conversion, I suppose that there is no other choice than exporting the database with populse_db v1 in a standard format such as JSON and then recreate this database with v2. For Mia, it is necessary to have special exporting code for the few fields attributes that were stored in an internal extension of database in v1. In v2, they are stored in a standard collection. If you think it can explain the test failure, I can help for the database conversion.

**Comment by denisri** [comment]
I did not know either until yesterday ;) and yes, that's more or less what I did to convert, althrough I was too lazy to cleanly export to json, I queried the database and copy/pasted dicts in a script which populated the v2 database later. So yes I possibly missed a few internals but I don't know enough about them, and even don't know if this is actually the cause of tests failures.
For instance some tests expect a database with a "current" collection containing 9 scans (documents), where I only have 8 - but I already find 8 in the v1 database, so I'm not sure.

**Comment by denisri** [comment]
Looking at it again I realized that the database I had converted was wrong:
* there was a missing item in it
* the documents order was wrong. This is because project.session.get_documents_names() and project.session.get_documents() apparently do not return documents in the same order. I have fixed my conversion, and re-converted the database. After that it has 9 items as it should.

But I now realize that with populse_db 1, tests were not modifying the database of this test project_8. But using populse_db 2 the database is altered during the first tests, and one of its documents is probably removed at some point.
Is v1 working in a "read-only" mode (without any commit) until a save/commit operation is explicitly called ? And does v2 commit things automatically ? This would explain things...

**Comment by sapetnioc** [comment]
Probably yes. In v1, especially when cache was used, it was necessary to
explicitly commit changes to put them in the database. In v2, all changes
are directly stored in the database using a transaction. The transaction is
implicitly created at the beginning of the with statement and terminated at
its end (rolling back modifications if the exit is due to an exception). If
it can help for testing, we could add a read-only parameter where changes
would always be rolled back.

**Comment by denisri** [comment]
By copying the whole test project directory (and database) to another temporary location before each test using it, I get far fewer failures (and an unmodified database at the end of tests). A few are still failing (maybe documents order in the database but I'm not sure yet).
Not sure it was a good idea to assume the database would not be modified in former tests anyway...

**Comment by denisri** [comment]
It's now working using populse_db v2.
There is a PR here: #165
However it only works with populse_db branch 2.0, so we have to decide whether to merge populse_db 2.0 into master or stick with this branch.

**Comment by sapetnioc** [comment]
There is a need to upgrade populse_db to 2.0 for some projects because some features (such as thread safety of API) are required. There is a [populse_db PR for that](https://github.com/populse/populse_db/pull/41). Before we validate this PR, we must decide whether populse_mia should depend on populse_db v1.1.3 or if PR #165 should be merged.

**Comment by servoz** [comment]
Currently the mia V2 is working with:
- mia: populse_db2_capsulengine branch
- db: 2.0 branch
- mia_processes: 2.0 branch
- all other populse packages in master branch.

V1 of mia correspond to all populse in master branches.

There are still some improvements, regression corrections to be done to be able to merge everything on the master branches and to officially release the V2. However we can already say that now mia is compatible with populse_db V2.
To make easier the last improvement work before the V2 release, I am bringing a particular effort to close as much as possible all the old tickets, in order to start again on clean tickets in connection with these improvements to be carried out.
So I think this ticket can be now closed.
