### ISSUE TITLE
MIA crashes when saving a pipeline is aborted

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#15]
How to reproduce:

- open MIA
- go to the PM tab
- Pipeline > Save pipeline
- in the file selection dialog, select cancel
-> crash

This comes about, since in PipelinEditor.save_pipeline we first add .py if the extension is missing, and later check for empty filenames. I will submit a merge request to fix this.

**Comment by servoz** [comment]
Closed by JanWP@5971a51
