### ISSUE TITLE
[general discussion] Setting up a different database for each tab in the mia pipeline manager

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#150]
Following issues #142, #143 and maybe #149 (problem1), I believe that to solve all the problems raised, and only partially solved for some with the current mia architecture, we should consider instantiating a different database for each open tab in the Pipeline Manager of Mia. After reflection, the current architecture does not really meet the needs generated by the possibility of opening several tabs, which necessarily leads to inconsistencies and conflicts in the case of a single database opened in mia. This is a non-negligible change that would require a serious reflection beforehand because the current code will certainly have to be modified on a scale that I don't fully understand yet. I open this ticket so that everyone can bring his reflection to this change.
- Is it really desirable?
- What are the changes and functionalities that should be implemented?

**Comment by servoz** [comment]
- By default, when mia is launched, a first database is created and will correspond to the first tab (by default open in the Pipeline Manager. This is the current operating state of mia, no code to modify).
- Each time a new tab is opened, a new database will be instantiated. So we change of paradigm in mia, because in this case a database is an object belonging to a tab whereas currently only one database is designed to work in mia (which poses many problems, which we have encountered in several previous tickets, between the different tabs, and which I will not develop here). I'm not sure to see all the implications of this change yet, but I expect side effects and a significant change in the code in this direction. That's why if we're going to make this change, it would be better to have thought about it before starting.
- I assume that many of the tools needed for the new operations already exist in the mia and will simply have to be adapted. I will try to rationalise what this change would imply, feel free to complete or make corrections, etc.

**Comment by servoz** [comment]
This is a point to discussion for V2. It is not trivial and must be accepted or rejected (and not kept unanswered), as a change in philosophy and coding depends on it.

**Comment by LStruber** [comment]
Since the resolving of issue #252 (setting the initialization as the first step of the run), the question of having different database for each tab no longer arises (or is at least less important).
Indeed, the major (only ?) source of database conflicts was the possibility for the user to initialize a pipeline in a tab, and use the results of initialization (which do not exist on hard drive!) in another pipeline/tab.

Now (commit f1e29bfd7a233aa9d4756c599e2dbb2b04a03d86), only existing data is referenced into the database which avoid the use of non-existing files in a pipeline.

**Comment by servoz** [comment]
> Since the resolving of issue #252 (setting the initialization as the first step of the run), the question of having different database for each tab no longer arises (or is at least less important).
Indeed, the major (only ?) source of database conflicts was the possibility for the user to initialize a pipeline in a tab, and use the results of initialization (which do not exist on hard drive!) in another pipeline/tab.
Now (commit f1e29bf), only existing data is referenced into the database which avoid the use of non-existing files in a pipeline.

@LStruber , you are absolutely right and I believe that this ticket can now be closed.
