### ISSUE TITLE
tests cannot succeed when an existing config exists

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#159]
**Describe the bug**

Configuration tests assume the config is empty, but for a user/developer install it is generally not.
Instantiating a populse_mia.software_properties.Config object automatically loads a saved config, thus contains unexpected values and makes tests fail.

**Generated error**
```
======================================================================
FAIL: test_mia_preferences (__main__.TestMIADataBrowser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/test.py", line 542, in test_mia_preferences
    self.assertEqual(config.get_mri_conv_path(), "")
AssertionError: '/home/riviere/neurosvn/populse/mri_conv/master/MRIFileManager/MRIManager.jar' != ''
- /home/riviere/neurosvn/populse/mri_conv/master/MRIFileManager/MRIManager.jar
+ 


======================================================================
FAIL: test_project_properties (__main__.TestMIADataBrowser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/test.py", line 722, in test_project_properties
    self.assertEqual(saved_projects.pathsList, [])
AssertionError: Lists differ: ['../../../../../../../../../../home/riviere/data/populse_projects/proj1'] != []

First list contains 1 additional elements.
First extra element 0:
'../../../../../../../../../../home/riviere/data/populse_projects/proj1'

- ['../../../../../../../../../../home/riviere/data/populse_projects/proj1']
+ []

```

**To Reproduce**
```python3 -m populse_mia.test```

**Expected behavior**
Tests results should not depend on existing configuration values

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Populse_MIA version 1.3.0 (git master)

**Additional context**

**Comment by servoz** [comment]
Yes it's true and so far I was testing on my station using python3 -m populse_mia (which uses ~/.populse_mia config which I leave in the initial installation state), while for development I use the main.py of my development directory (which uses the config in this directory). I think you have a different philosophy because you don't use the possibility to work in development with a development directory (we have already discussed this). I like my philosophy and you like yours, which is normal ! I will look to change that (although it's not so easy because as the config can be different for each one it's not easy to test in this case ...).

**Comment by denisri** [comment]
Removing the config file makes all tests fail:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/riviere/neurosvn/populse/populse_mia/master/properties/config.yml
```
and then I cannot restart populse_mia: I get a popup "Please select the MIA path (path with the processes, properties & resources directories):". When I enter the correct path (for me `/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia`, as it was set before and which actually contains the `processes`, `properties` and `resources` directories) I keep getting an error message "Error: Please select the MIA path (path with the processes, properties & resources directories):", so I cannot go further.
Moreover the encrypted config file makes it impossible to debug or understand config issues...

**Comment by denisri** [comment]
I'm using `python3 -m populse_mia`
I must admit I have not looked at differences between this call and calling the `main.py` file with full path. I use the first one because it doesn't need to `cd` or call a complete path (so it's just laziness), but it changes the config file in populse_mia sources. I was not really aware there was a difference between these 2 ways of running mia.

**Comment by servoz** [comment]
if you use python3 -m populse_mia it wull use ~/.populse_mia.
if you use python3 main.py it will use properties in the directory containing the main.py (and also the python/populse_mia in that directory, not the one in the site package)

**Comment by servoz** [comment]
yes i understand, it's why i have this alias in my env:

`alias mia='pwd_orig=$PWD; cd /home/econdami/Data/Git_Projects/populse_mia/python/populse_mia; python3 main.py; cd $pwd_orig'
`

like that i use mia when i work in dev and python3 -m populse_mia when i want to be as user (almost never or just for testing ). Nevertheless, your ticket makes sense and I'm going to look at making config testing more universal (we have to think about a config that everyone would have ... not simple ....) in fact my idea is that testing is a developer thing, and in my philosophy there's a clear separation between developers config and users config....

**Comment by denisri** [comment]
OK I get it, it's a way of handling several populse_mia installs, one using pip and one using git sources. However I only have the git version (+ PYTHONPATH pointing on it)  thus both ways are the "development mode" for me ;)
Never mind it's not really the point for this ticket.

**Comment by servoz** [comment]
Oh! I was also working on this ticket... I'm going to read what you've done and hopefully what I've started will easily fit into this!

**Comment by servoz** [comment]
Well, well ... finally I'm gonna throw away what I started... What you've done is much better  :-(((((( ... ;-)
