### ISSUE TITLE
[general discussion] "Delete package" functionality for a brick in a module with other bricks.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#161]
Currently, if we use "Delete package" functionality, the corresponding module, the entry in \_\_init__.py and in properties/process_config.yml are deleted, if the corresponding brick is the only one in the module.

Likewise, if it's a real package (in the python sense, a folder), it will be deleted.

On the other hand, if it's a brick (a class in the python sense) in a module containing several others, nothing is done. 
It's better than a blind deletion of the module containing other bricks (classes) that have not been asked to be deleted! However, we will have to think about how to handle this case:
- rewriting the module without that brick (possible but not easy, side effects possible) + entry in \_\_init__.py (easy) and in properties/process_config.yml (easy) deletion
or
- ... do not change the current situation (in this case it would be better to provide a message for the user who will certainly not understand why the brick he asked to delete is still in the brick library!)

This is not a priority because it is not really a bug, rather an improvement.

I open this ticket to keep this in mind.

**Comment by servoz** [comment]
After a private discussion with @LStruber , it was decided :

We take an intermediate position (between doing nothing if the brick - the class - is in a module with other bricks - classes - and doing the deletion).

- We code a pop-up that says something like "the brick(s) cannot be deleted because it belong(s) to a module with several other bricks". We Indicate in the pop-up that in order to perform this operation we will have to "delete all the following bricks:" and list them (all bricks/classes of the module). Add "Delete all" and "Cancel" buttons. Also indicate in the pop-up that this operation will be definitive (no possibility to undo afterwards).

- Some a priori difficulties detected to close this ticket:
  - How to detect the classes (bricks) in the module?
    - Parsing and detecting the `class` keyword at the beginning of the line (error prone?)?
    - Look in the module \_\_init\_\_.py which should normally be up to date (error prone if not up to date?).
  - Be sure to handle the case of several bricks in several different modules.
  - Be sure to update the \_\_init\_\_.py module in the case of a brick / class deletion.

Of course, we keep the rule that bricks from the nipype, mia_processes and capsul packages cannot be deleted (they can only be made invisible). The final removal of bricks can only take place for the other bricks (User_processes, etc.).

**Comment by LStruber** [comment]
@servoz do you have an example of a module containing several bricks other than nipype, mia_processes and capsul packages ? It seems that saving pipelines (User_processes) only create "single" classes

**Comment by servoz** [comment]
Yes you are perfectly right.

Nypipe, mia_processes and capsul being python packages we made the choice not to allow to delete bricks/processes/classes in them (which wouldn't really make sense, especially since they are mandatory packages for mia) and to only allow to make them invisible in the manager pipeline.

On the other hand for all other process/bricks libraries in the pipeline manager the user may want to really remove (not just make invisible) all or part of the bricks.

Indeed in the case of a pipeline saved in Mia it will be only a class in a module and this simple case is already managed in Mia (if i remember well).

There are other cases. Two come to my mind. 
1- The user is also a developer and he codes these bricks. In this case he (or other people working with him) may want to gather several bricks/classes in one module.

2- mia allows loading bricks developed elsewhere. In this case we come back to the first point.

There are certainly other cases that I don't think of right away, or not!

As an example [here are 4 bricks ](https://mycore.core-cloud.net/index.php/s/AEMIoaboCefPaGf) (in fact they are just bricks of mia_processes that I put there just for the example) in a module that you can load in mia (see More > Install processes > From zip file)

**Comment by LStruber** [comment]
I proposed a solution in branch fix#161 to fix the issue as explained by @servoz few days ago.
I tested the branch with the libraries I had, and it seems to works. To detect the classes (bricks) in the module, I choosed to look in the module `__init__.py` which should normally be up to date.

Although I tried to handle all cases when reading `__init__.py` (for example multiline import with parenthesis), I may have miss something. Then I would be more comfortable with merging into master if @servoz (or others) could check on his (their) side(s) if (at least) main cases are taken into account. Thanks

**Comment by servoz** [comment]
I've spent some time on this ticket, it's the kind of ticket that makes headache.
I made some modifications to allow to manage (all?) most of the cases.
Now the most classic cases are managed I think.
However I think there are still a few cases that are not yet properly handled.
I need to write several library cases to be able to test this properly.
I will work on this ticket ASAP.

**Comment by servoz** [comment]
Ouch It's like the pandora box ...
While testing the bricks deletion, I notice that the installation by More > Install processes does not manage all the cases either ...
So I'm going to look at the whole installation / removal of non mandatory libraries (nipype, capsul, mia_processes).
These are important Mia's features for the user.
Indeed, one can imagine and work hard on the functioning of Mia, without bricks Mia will not be useful for much (except to provide all the bricks used to the user in capsul and mia_processes, which I doubt because the field of action is just too extended).
So we need a management system (add, delete, invisible) for the pipeline manager to work perfectly and in all cases.
I do it.
I don't open a new ticket for that.
We will close this one when the installation/deletion set will work properly in any case.

**Comment by servoz** [comment]
Your solution was good @LStruber.
I just tried to complete to cover all the cases...
 It was a meticulous work thus I hope we didn't now forget any case...
