### ISSUE TITLE
"add process" from the pipeline editor crashes MIA

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#162]
**Describe the bug**
The application crashes (exception in a Qt slot) when adding a process from the pipeline editor GUI (popup menu)

**Generated error**
```
Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/user_interface/pipeline_manager/pipeline_editor.py", line 339, in add_process
    class_name = class_process.__name__
AttributeError: 'bool' object has no attribute '__name__'
```

**To Reproduce**
1. Go to the pipeline manager tab
2. Right-click on the pipeline editor and select "add process in pipeline"
3. See error

**Expected behavior**
No crash. No error. A process should be added after its name/class is entered (or the feature should be removed)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Populse_MIA version: 1.3.0 (master)

**Additional context**
The method ```add_process``` from ```capsul.qt_gui.widgets.pipeline_developper_view.PipelineDevelopperView``` is overloaded in ```PipelineEditor``` with different parameters, a different meaning, and different behaviour.

**Comment by servoz** [comment]
I never used this functionality ....  I'm gonna take a look ASAP
