### ISSUE TITLE
[continuous integration] populse_mia tests randomly crashed in Travis-ci

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#168]
**Describe the bug**
segfaults during tests:
@servoz said:
> Ok all the Travis-ci are now ok. it's very annyoning . I am not sure but this random segfaults could comes from the virtual environment in Travis. Indeed the segfaults is always coming with this kind of message:
.qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 1732, resource id: 2097212, major code: 42 (SetInputFocus), minor code: 0
We nether observed this problem on physical machine or with appveyor.

**Comment by denisri** [comment]
Yes crashes happen only using xvfb on the travis-ci server. I don't observe this on my machine, so I suspect a problem in the xvfb version used on travis-ci.
Anyway there might be things we can do:
* the tests open many Qt windows and never closes them. When not running in xvfb I observe dozens of windows and popups showing up one over the previous ones. A few close during tests, but most of them stay visible until all tests are done. Maybe closing popups as soon as they are not used would improve the stability ?
* or taking care of closing all GUI windows at the end of tests, and deleting python variables relating to them. This last aspect is not always easy to fix as python reference counting is tricky to control when leaving an application. But I think the tests often crash before the end of tests, so I guess this is not the good way to fix things.
* is it possible to upgrade xvfb on travis test systems ?

**Comment by servoz** [comment]
Ok, those are good ideas. As soon as possible, I'll try to find time to see this issue ...

**Comment by servoz** [comment]
Tests currently impacted:
- test_add_tag (__main__.TestMIADataBrowser)
- test_mia_preferences (__main__.TestMIADataBrowser)
- test_send_documents_to_pipeline (__main__.TestMIADataBrowser)
- test_z_init_pipeline (__main__.TestMIAPipelineManager)
