### ISSUE TITLE
run step is crashing (major remark)

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#171]
- run step is crashing (major remark)
 When the pipeline was launched, the following exception was raised: 
```
Error during workflow execution. Status=('finished_regularly', 1, None, None).
The workflow has not been removed from soma_workflow and must be deleted manually. 
Failed jobs: [24]
Aborted/killed jobs: []
============================================
---- failed job info ---
* job: 24: smooth1
* exit status: finished_regularly
* commandline:
'python3' '-c' 'from capsul.api import Process; Process.run_from_commandline("mia_processes.preprocess.spm.spatial_preprocessing.Smooth")'
* exit value: 1
* term signal: None
---- env ----
None
---- configuration ----
{'capsul_engine': {'uses': {'capsul.engine.module.spm': 'any', 'capsul.engine.module.matlab': 'any'}}, 'capsul.engine.module.spm': {'config_id': 'spm12', 'config_environment': 'global', 'directory': '/usr/local/SPM/spm12', 'version': '12', 'standalone': False}, 'capsul.engine.module.matlab': {'config_id': 'matlab', 'config_environment': 'global', 'executable': '/usr/local/MATLAB/R2019b/bin/matlab'}}
---- stdout ----

---- stderr ----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'capsul'
 ...
```
If i remember well this is what i observed with the capsulengine branch last week, so i guess it is not exclusively linked with this PR.
We should pass the sys.path to the command` 'python3' '-c' 'from capsul.api import Process; Process.run_from_commandline("mia_processes.preprocess.spm.spatial_preprocessing.Smooth")' `

(if you remember, after a meeting I made a modification in the main.py to add in the sys.path the packages in development instead of using the ones in the site-package. So I removed everything from the site-package on my station to avoid starting with one package and continuing with another when running mia ...).

_Originally posted by @servoz in https://github.com/populse/populse_mia/pull/165#issuecomment-651804751_

**Comment by denisri** [comment]
@servoz added:
 populse/capsul#167

**Comment by denisri** [comment]
The problem here is that populse_mia changes things in the sys.path interally at the application level, and this change is not transmitted to processing jobs, which do not go through the mia application launch tricks.
Moreover as Yann commented on the PR populse/capsul#167 the jobs may run on a different machine, different system, different environment, so replacing the sys.path for the client one is not an option. We must find something else (configuration ?) to handle this. Moreover this can also be seen rather as an installation issue.

**Comment by denisri** [comment]
does populse/capsul@03a7154335782653b7a41b546fa3d2a5fb769ba9 help ?

**Comment by denisri** [comment]
This commit in capsul adds a python config module which allows to specify python executable and pythonpath settings for each computing resource. Unforfunately there is no GUI for that yet and the user cannot easily set it yet.

**Comment by servoz** [comment]
as I've answered [here](https://github.com/populse/capsul/pull/167), I agree that we must find another way to do...

**Comment by servoz** [comment]
In order to simplify the treatment of issues concerning the passage to db 2.0, capsulengine (capsul 3.0 ?) and mia 2.0 I try to group all the tickets opened on this subject in #180. Moreover the problem raised by this issue now seems to be solved. I therefore close this issue.
