### ISSUE TITLE
Can't create or save project with 2 hard drives Windows 10

### ISSUE THREAD

**Issue by saldanhag** [populse/populse_mia#173]
I'm working with populse_mia 1.3.0, python 3.8.3 on Windows 10.
I have two hard drives (1 SSD where populse_mia in installed and 1 hard drive where i want to put the project file).

When i want to save or create a project I got the exception:
 `"ValueError: path is on mount 'E:', start on mount 'C:'" `.

The problem comes from the populse_mia/user_interface/pop_ups.py module:
  - line 1702 when I use New project:
    `self.relative_subpath = os.path.relpath(self.path) ` (PopUpNewProject.get_filename())

and

  - line 3193 when I use Save project as:
    `self.relative_path = os.path.relpath(entire_path)` (PopUpSaveProjectAs.return_value())

**Comment by servoz** [comment]
On Windows, a relative path doesn't even *exist* if the two directories are on different drives ... This is not the case with a real OS like linux ...
With virtualisation, we can hope to do without Windows and we can close this ticket!
