### ISSUE TITLE
merge has imported spurious files

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#176]
In merge 3ab731d754cf0a0dad741b405e51e32069bf616f "merge branch 'oswindows'", many many files have been updated, and all built docs have been imported back in git, which had been removed and replaced with an auto-build of docs in travis-ci.
These many changes make it almost impossible to merge master into the new branches populse_db_2, capsul_engine etc. Or at least it's in a state I don't understand now and I don't know how/what to merge.

**Comment by servoz** [comment]
unless I'm mistaken, it's just the documentation @saldanhag made for windows, no code change. Did we make a mistake? You want me to look at something?

**Comment by denisri** [comment]
I just tried a merge from master to one of my branches (populse_db_2 actually) and saw that there were many many added files, which are built docs - we decided not to put them under git (we actually removed them a few months ago) and let travis build them, thus I was surprised (and a bit confused). There were conflicts in the code too, and maybe this is perfectly normal, but then I did not globally understand the state of the code...
What should we do with these windows docs, and what are they ? Are they just a sphinx build of the docs from a windows machine (which should produce exactly the same docs as other systems), or is there anything different here ?

**Comment by saldanhag** [comment]
Normally, in oswindows and in the main code (not the documentation), I erased every print that I used to track the problem. Maybe the problem comes from the fact that I use Atom to code and it has the bad habits to erase automatically every blanck when I save a file. So maybe the merge errors are mainly dur to that.

**Comment by denisri** [comment]
Well I have apparently mixed up many things in my head... the docs have never been automatically generated on the populse_mia project... This has been done in other projects (capsul, populse_db, ...) but not populse_mia. My mistake, sorry.
But I guess this would be a good idea to set it up instead of putting HTML docs under git.
OK then I'll try that merge again and see what gets out if it.

**Comment by servoz** [comment]
Sorry, I wasn't online ... yes that's exactly what we did for mia_processes but not for populse_mia yet. we'll have to do it for populse_mia as well. It's on my todo list, but as we still have more urgent things it's still below in the stack ... thanks for fixing the conflict for merge !
