### ISSUE TITLE
Data browser : Memory usage growing until mia crash : mini_viewer.py

### ISSUE THREAD

**Issue by urlub** [populse/populse_mia#177]
**Description**
In the databrowser when you clic on a file/scan then an other, then other, then back to first, then other and so on, populse_mia crash.
with this error

**Traceback**
Exception hooking in progress ...
Clean up before closing mia done ...
Traceback (most recent call last):
  File "/home/ppi/Documents/DEV/populse_dev/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 2101, in selection_changed
    self.data_browser.connect_mini_viewer()
  File "/home/ppi/Documents/DEV/populse_dev/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 333, in connect_mini_viewer
    self.viewer.verify_slices(full_names)
  File "/home/ppi/Documents/DEV/populse_dev/populse_mia/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 775, in verify_slices
    self.show_slices(file_paths)
  File "/home/ppi/Documents/DEV/populse_dev/populse_mia/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 575, in show_slices
    self.indexImage(idx)
  File "/home/ppi/Documents/DEV/populse_dev/populse_mia/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 457, in indexImage
    idx, self.img[idx].get_fdata()[:, :, sl3D, sl4D].copy())
  File "/home/ppi/.local/lib/python3.6/site-packages/nibabel/dataobj_images.py", line 348, in get_fdata
    data = np.asanyarray(self._dataobj).astype(dtype, copy=False)
  File "/home/ppi/.local/lib/python3.6/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home/ppi/.local/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 355, in __array__
    raw_data = self.get_unscaled()
  File "/home/ppi/.local/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 350, in get_unscaled
    mmap=self._mmap)
  File "/home/ppi/.local/lib/python3.6/site-packages/nibabel/volumeutils.py", line 509, in array_from_file
    offset=offset)
  File "/home/ppi/.local/lib/python3.6/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [Errno 12] Ne peut allouer de la mémoire

**Expected behavior**
Clic on a file/scan show a preview in mini image viewer, release the memory when file/scan selection change. Is it right ? 

**Desktop**
 - OS: Ubuntu
 - Populse_MIA version 1.3.0

**Additional context**
Done with populse_mia philips test data

**Comment by servoz** [comment]
thanks for opening a ticket in populse_mia!
I has spent a while clicking on all databrowser documents without reproducing this exception. Can you please produce a minimal, reproducible example (with the database you are using [as in this example](https://github.com/populse/populse_db/issues/40)). If we can't reproduce the exception raised, it is difficult to fix this issue !T

**Comment by urlub** [comment]
If I remember well, you have may be 32Gb of of memory. You probably don't reach the limit. 
To see whats happen more clearly, open a monitor to see memory usage 
![Capture d’écran de 2020-07-29 09-24-05](https://user-images.githubusercontent.com/37933068/88770402-0ea4fe80-d17e-11ea-9783-bfacefa4a8c7.png)
In this screenshot you see the memory growing during clics on each 2 scans until memory full and application crash,  freeing the memory
![Capture d’écran de 2020-07-29 09-38-10](https://user-images.githubusercontent.com/37933068/88770959-d356ff80-d17e-11ea-9b1b-63d807a57f93.png)
the data used, coming from populse_mia philips test dataset

**Comment by servoz** [comment]
Without a minimal step to reproduce and the data to use, it will be difficult to solve this issue.

**Comment by denisri** [comment]
I didn't take time to report this, but I experience exactly the same thing, using the same test dataset, on a laptop with 8Gb of memory. It seems that data in the mini viewer is never freed, and when you click alternatively on both images (T1 MRI and functional data) several times, the memory usage grows again and again.

**Comment by servoz** [comment]
OK, so we can exclude a problem related to input data (I am wary of spending time on an issue when the real problem could come from something else, that's why I hesitate to work on a ticket if neither the data that produced the problem are provided, nor a minimum procedure to reproduce this problem).

OK, so it would be necessary to look at it in order to free the memory when an image is not selected any more (it will be necessary to take care not to free if several images are selected to compare them in the mini_viewer!

To be seen as soon as possible (however at the moment there are a lot of things to see ...)

**Comment by urlub** [comment]
I saw a problem to show slices in miniviewer.py
The checkbox "Show all slices" become grey, no slides and no action is possible
I solved it by change in mini-viewer.py replace img by im in
    def image_to_pixmap(self, im, i):
            #im_2D = im.get_fdata()[:, :, i].copy()
            im_2D = np.asarray(im.dataobj)[:, :, i].copy()
            im_3D = np.asarray(im.dataobj)[:, :, :, i].copy()
            im_4D = np.asarray(im.dataobj)[:, :, :, :, i].copy()

The great new is that the memory leak has disapeared. thanks Servoz

**Comment by servoz** [comment]
This is not really the right place to talk about the "Show all slices" checkbox (it's a ticket concerning the issue of free memory when you click in the mini-viewer ...).
Anyway, I reproduce the issue and your fix seems to be valuable!
Please, push your fix on master (I'll propagate it in populse_db2_capsulengine branch later).

**Comment by urlub** [comment]
I put it because it concerns the modifications done for this issue

**Comment by servoz** [comment]
oops you are right !!! all my fault it's a typo that i introduced when fixing this issue (too fast paste).
Forget the fix, I'm going to correct my typo by myself!
thanks!
