### ISSUE TITLE
Process library not updated correctly when saving pipeline multiple times

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#18]
When modifying and saving a pipeline to the same file, the compiled version of the module in __pycache__ is not updated. Importing the module in a new pipeline imports the old version.

How to reproduce:
- open MIA
- in PM, add a module to the "New Pipeline", for example spm>smooth
- export the mandatory input and output plug
- save the pipeline to a file in the user directory, say 'toto.py'
--> a file toto.cpython-36.pyc is generated in \_\_pycache\_\_
- export an additional input plug
- save the pipeline again, choose the same file, confirm overwrite
--> the file toto.cpython-36.pyc in \_\_pycache\_\_ remains unmodified
- open a new pipeline editor
- drag and drop 'toto' from the User_processes
--> the version with a single input plug is imported

When closing MIA and opening again, the new version will be imported.

This bug may be related to the one I have with the Tab Name in Qt, so would be interesting to see if anybody else can reproduce this. 

I have traced the code for saving the file, but have not found the place where something is missing. My guess would be PipelineManagerTab.updateProcessLibrary() or further down in PackageLibraryDialog.add_package().

**Comment by servoz** [comment]
Exactly the same thing for me. I think we can estimate it as a bug to fix!

**Comment by JanWP** [comment]
I am tempted to add a feature request to that: It would be nice to have both "Save" and "Save as..." menu entries for pipelines. I find I often would like to save the current pipeline to its current location. Having to select the same file and confirm overwrite each time seems unnecessarily cumbersome.

Behind these buttons, I could imaging a SaveChoice function of a spirit similar to that of the main window, which performs
- save if the user clicked save and the pipeline was saved before
- save_as if the user clicked save and the pipeline was never saved
- save_as if the user clicked save_as and chooses a new location
- save if the user clicked save_as but chooses the previous location again

**Comment by JanWP** [comment]
Regarding the location where the compilation happens, could this be the place:

`.../dist-packages/capsul-2.1.2-py3.6.egg/capsul/study_config/process_instance.py:136`

**Comment by dhrbn** [comment]
I'll wait the merge of this pull request https://github.com/populse/populse_mia/pull/30 to add the save/save_as behavior that @JanWP has mentioned previously

**Comment by servoz** [comment]
#30 is now merged.

**Comment by dhrbn** [comment]
I was going to add this save/save_as functionality in the Pipeline Manager and thought it could be convenient to add a "Ctrl+S"/"Ctrl+Shift+S" shortcut. Problem: these shortcuts already exist (in the menu-bar, so at the MainWindow level and correspond to the save/save_as actions of the project). 

Should we:
- disable the save/save_as actions of the project when we are in the Pipeline Manager ? 
- set different shortcuts to the save/save_as action of the Pipeline Manager ?
- set no shortcut for the save/save_as action of the Pipeline Manager ?

**Comment by dhrbn** [comment]
The Ctrl+S signal should be linked to a generic action that depends on the current tab

**Comment by dhrbn** [comment]
Closed by https://github.com/populse/populse_mia/commit/c00c2da86689b94b0a1f926f2d821a49818926c6
