### ISSUE TITLE
Populse_mia crashes in miniviewer

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#182]
**Describe the bug**
Populse_mia crashes when clicking on a data. It occurs within the mini-viewer. It happens on one of my machines, apparently not on another. Maybe different versions of skimage ?
The problem is introduced in the fix for #177. If I get to the previous commit, the problem disappears.

**Generated error**
```
Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/data_browser.py", line 2134, in selection_changed
    self.data_browser.connect_mini_viewer()
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/data_browser.py", line 332, in connect_mini_viewer
    self.viewer.verify_slices(full_names)
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 795, in verify_slices
    self.show_slices(file_paths)
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 599, in show_slices
    self.image2DModifications(idx)
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 421, in image2DModifications
    anti_aliasing=False)
  File "/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py", line 178, in resize
    preserve_range=preserve_range)
  File "/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py", line 879, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 71, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
```

**To Reproduce**
1. open populse_mia
2. open a project containing any data
3. click on an image in the data browser
boom.

**Expected behavior**
no crash and data displayed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 + casa-distro in singularity
 - Populse_MIA version:  1.4.0-dev+ab13c366 (branch `populse_db2_capsulengine`)
- skimage.__version__ = '0.14.5'

**Comment by servoz** [comment]
I think I have already seen this exception with skimage . I look at this as soon as possible

**Comment by denisri** [comment]
On another machine with skimage version 0.15.0, I don't have the problem. Do we have to upgrade ? I think we should at least test or try...except something in populse_mia and disable the viewer without crashing if something goes wrong there.

**Comment by servoz** [comment]
We had already a problem with skimage and this exception ... #153

**Comment by servoz** [comment]
does the Big-endianIssue branch fix the problem on the station where it doesn't work and doesn't produce new problems on the station it was working ... ?

**Comment by servoz** [comment]
this branch is working fine for me with:
```
$ pip3 show scikit-image
Name: scikit-image
Version: 0.15.0
Summary: Image processing routines for SciPy
Home-page: https://scikit-image.org
Author: None
Author-email: None
License: Modified BSD
Location: /home/econdami/.local/lib/python3.7/site-packages/scikit_image-0.15.0-py3.7-linux-x86_64.egg
Requires: PyWavelets, imageio, matplotlib, networkx, pillow, scipy
Required-by: 
```

and

```
$ pip3 show scikit-image
Name: scikit-image
Version: 0.17.2
Summary: Image processing in Python
Home-page: https://scikit-image.org
Author: None
Author-email: None
License: Modified BSD
Location: /home/econdami/.local/lib/python3.7/site-packages
Requires: pillow, matplotlib, scipy, imageio, numpy, tifffile, networkx, PyWavelets
Required-by: 

```

**Comment by denisri** [comment]
I had completely forgotten about #153 ;)
Your fix seems to work on both machines, thanks !

**Comment by servoz** [comment]
cool !

**Comment by urlub** [comment]
I have the same problem from fresh installation on ubuntu 20.04.
left or right click on image (here .nii diffusion) crash directly populse_mia

I read #153 and the scikit-image issue https://github.com/scikit-image/scikit-image/issues/4525 and solved it by add sk.img_as_float64(im2D) line 420 in miniviewer.py

Name: scikit-image
Version: 0.17.2

branch master

**Comment by servoz** [comment]
I only have an empty line for line 420 in the up to date populse_mia.user_interface.data_browser.mini_viewer module.
This is the last version of this module between line 419 and 435:

```
        if version.parse(sk.__version__) >= version.Version("0.14.0"):

            try:
                im2D = resize(im2D, display_size, mode='constant',
                              anti_aliasing=False)

            except ValueError:
                im2D = resize(im2D.byteswap().newbyteorder(), display_size,
                              mode='constant', anti_aliasing=False)
        else:

            try:
                im2D = resize(im2D, display_size, mode='constant')

            except ValueError:
                im2D = resize(im2D.byteswap().newbyteorder(), display_size,
                              mode='constant')
```

As I said to you in pm if you don't have these lines in your module, please update it !

**Comment by urlub** [comment]
I have the same problem from fresh installation on ubuntu 20.04.
left or right click on image (here .nii diffusion) crash directly populse_mia

I read #153 and the scikit-image issue https://github.com/scikit-image/scikit-image/issues/4525 and solved it by add sk.img_as_float64(im2D) line 420 in miniviewer.py

Name: scikit-image
Version: 0.17.2

populse_mia branch master

i'm not sure this is the right way to solve this for you ? i saw 3 differents propositions in the sk-image issue 4525 to do that. i use this one because it seems simple and works.

**Comment by servoz** [comment]
please can you past here your module between line 419 and 435 ?

**Comment by urlub** [comment]
I don't understand why i have the last modification even after a pull or checkout from master ?

the lines of codes mini_viewer.py 419-435 :
```
        if version.parse(sk.__version__) >= version.Version("0.14.0"):
            im2D = resize(sk.img_as_float64(im2D), display_size, mode='constant',
                          anti_aliasing=False)
        else:
            im2D = resize(im2D, display_size, mode='constant')

        # Rescale image while handling Nans and infinite values
        im_mask = np.isfinite(im2D)
        if np.any(im_mask):  # if we have any finite value to work with
            # shift the lower percentile chosen to 0.0
            im2D -= np.percentile(im2D[im_mask], display_pctl)
            # determine max from upper percentile
            im_max = np.percentile(im2D[im_mask], 100.0 - display_pctl)
            if im_max > 0:  # avoid dividing by zero
                # re-scale to display range
                im2D *= (display_max - display_min) / im_max
            # shift lowest value to lower limit of display range

```

**Comment by servoz** [comment]
u don't have the last version.
The last version is in populse_db2_capsulengine branch ... it is the branch of preparation for the V2 ...
If you really need the miniviewer now, tell me and I'll do the modification on master ...

**Comment by urlub** [comment]
no thanks, i go to branch v2
