### ISSUE TITLE
extra files in derived_data folder when using spm jobtype==estimate, in V2

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#189]
- launch mia
- open a project with at least one bold.nii (+one anat.nii in example above).
- go to Pipeline Manager
- drag and drop the mia_processes Realign brick/process
- change only jobtype==write to default parameters and set the bold.nii for in_files parameter, then initialise and run

**Result:**
- in database:
![Screenshot from 2021-05-12 17-37-53](https://user-images.githubusercontent.com/37933899/118006018-318a5300-b34b-11eb-8930-f12729e12570.png)
- in data directory:
```
ls -l *
derived_data:
total 458884
-rw-rw-r--. 1 econdami econdami    977248 May 12 17:34 meanalej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii
-rw-rw-r--. 1 econdami econdami 468910432 May 12 17:34 ralej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii
downloaded_data:
total 0
raw_data:
total 621804
-rw-rw-r--. 1 econdami econdami      8435 May 12 17:31 alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.json
-rw-rw-r--. 1 econdami econdami 468910432 May 12 17:31 alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii
-rw-rw-r--. 1 econdami econdami     10945 May 12 17:31 alej170316-IRMFonct.+perfusion-2016-03-17083444-1-T13DSENSE-T1TFE-000425.000.json
-rw-rw-r--. 1 econdami econdami 167772512 May 12 17:31 alej170316-IRMFonct.+perfusion-2016-03-17083444-1-T13DSENSE-T1TFE-000425.000.nii
-rw-rw-r--. 1 econdami econdami       493 May 12 17:31 logExport_2021-05-12_15-15-36
-rw-rw-r--. 1 econdami econdami       606 May 12 17:31 logExport_2021-05-12_15-15-36.json
```
=> everything is as expected!

- launch mia
- open a project with at least one bold.nii (+one anat.nii in example above).
- go to Pipeline Manager
- drag and drop the mia_processes Realign brick/process
- keep all the default parameters (jobtype==estwrite) and set the bold.nii for in_files parameter, then initialise and run

**Result:**
- in database:
![Screenshot from 2021-05-12 17-41-38](https://user-images.githubusercontent.com/37933899/118006903-f50b2700-b34b-11eb-8410-6330c0b1f2a2.png)
- in data directory
```
ls -l *
derived_data:
total 1080732
-rw-rw-r--. 1 econdami econdami      8435 May 12 17:38 alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.json
-rw-rw-r--. 1 econdami econdami     30912 May 12 17:40 alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.mat
-rw-rw-r--. 1 econdami econdami 468910432 May 12 17:40 alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii
-rw-rw-r--. 1 econdami econdami     10945 May 12 17:38 alej170316-IRMFonct.+perfusion-2016-03-17083444-1-T13DSENSE-T1TFE-000425.000.json
-rw-rw-r--. 1 econdami econdami 167772512 May 12 17:38 alej170316-IRMFonct.+perfusion-2016-03-17083444-1-T13DSENSE-T1TFE-000425.000.nii
-rw-rw-r--. 1 econdami econdami    977248 May 12 17:41 meanalej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii
-rw-rw-r--. 1 econdami econdami 468910432 May 12 17:41 ralej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii
-rw-rw-r--. 1 econdami econdami     23280 May 12 17:40 rp_alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.txt
downloaded_data:
total 0
raw_data:
total 621804
-rw-rw-r--. 1 econdami econdami      8435 May 12 17:38 alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.json
-rw-rw-r--. 1 econdami econdami 468910432 May 12 17:38 alej170316-IRMFonct.+perfusion-2016-03-17083444-0-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii
-rw-rw-r--. 1 econdami econdami     10945 May 12 17:38 alej170316-IRMFonct.+perfusion-2016-03-17083444-1-T13DSENSE-T1TFE-000425.000.json
-rw-rw-r--. 1 econdami econdami 167772512 May 12 17:38 alej170316-IRMFonct.+perfusion-2016-03-17083444-1-T13DSENSE-T1TFE-000425.000.nii
-rw-rw-r--. 1 econdami econdami       493 May 12 17:38 logExport_2021-05-12_15-15-36
-rw-rw-r--. 1 econdami econdami       606 May 12 17:38 logExport_2021-05-12_15-15-36.json
```
=> in the database everything is good.
However, in the derived_data directory, it seems that bold.json, anat.nii and anat.json should not be there!

**Comment by denisri** [comment]
For `bold.nii/.json` we can consider it's normal, because the realignment process has a "`modified_in_files`" output parameter: SPM modifies the header of input images in order to store the realignment parameters in their header. In our view we consider that inputs are read-only, thus inputs which may be modified are copied and appear as an additional output parameter.
What is not normal is that this file is not indexed in the database.
For `anat.nii/.json` it's not normal, and strange, as the anat seems not to be used in any way in the process (do I miss anything ?)

**Comment by denisri** [comment]
It seems to be a bug in `FileCopyProcess` in [capsul](https://github.com/populse/capsul). I'm on it.

**Comment by denisri** [comment]
OK the bug id fixed in Capsul. And the remaining duplicated (modified) input(s) actually appear in the database, so thinks look OK for me. Do you confirm / agree ?

**Comment by servoz** [comment]
>  For bold.nii/.json we can consider it's normal, because the realignment process has a "modified_in_files" output parameter: SPM modifies the header of input images in order to store the realignment parameters in their header. In our view we consider that inputs are read-only, thus inputs which may be modified are copied and appear as an additional output parameter.
What is not normal is that this file is not indexed in the database.

The possibility jobtype==estimate offered by SPM is like a medal with a very interesting side and another one rather painful to manage (I will not detail but it is quite obvious that having the same file entering process/brick and leaving it modified can cause a mess...).
But after all, I think that it is not the real problem here.
Indeed, I agree with you about bold.nii, but I don't think bold.json should be copied or indexed in the database. 
By the way, bold.json is not indexed in the database before. 
In raw_data, we have the raw data (indeed :-) and bold.json can be found there, but we can consider that it is optional because if everything went well during the import of the data, all the metadata of bold.json were indexed in the database as a tag associated to bold.nii.
When we process a brick/process using as input bold.nii, it makes sense that bold.nii is copied in derived_data if jobtype==estimate, on the other hand for bol.json it is more questionable, because the brick can have changed or added tags for bold.nii (in derived_data) in the database.
From this moment bold.json does not reflect the tags of bold.nii in derived_data (but  bold.nii in raw_data).
I believe that the .json files should always remain in raw_data.

**Comment by servoz** [comment]
So, your fix seems to work quite well, in my opinion except for the copy of bold.json (vide supra).
Maybe I'm wrong or maybe for your applications it's important to copy bold.json (but in that case bold.json might not be synchronised with the database anymore)?

**Comment by denisri** [comment]
Well, this question is more complex than it appears. We are not using the .json in our applications thus don't "personally" need it, but the 1. BIDS standards, as far as I know, recommends (or imposes ?) to maintain .json files together with data files, so if we plan to comply with BIDS we will need to also carry this .json; 2. Some data formats are composed of several files (for instance the old Analyze format or corresponding variant of Nifti, .img/.hdr) and we don't have a generic means of knowing what is part of the same dataset (we probably need to handle data file formats in Capsul/Mia but for now we don't), 3. In our applications (older than BIDS and .json) we maintain an additional meta-info file (.minf which is pretty similar to json) that we need to carry with all files when they are here, 4. Some other software may expect to read the .json file to complement their metadata: if we don't write it side to the modified input file, such software will not be able to get the full set of metadata and might behave differently, even if we actually have the metadata in MIA database.

**Comment by servoz** [comment]
Ok for me to keep the .json then!
But we have to keep in mind that currently, the .json will be certainly not synchronised with the corresponding .nii (it is the .json of the input image, but in the case of an `estimate` calculation this image has been modified during the process) and when it is not an `estimate` calculation, only the .nii is available in derived_data directory (no associated .json) ...
So I think we can close this ticket.
