### ISSUE TITLE
Keeps the output in the database after several iterations without a run between each, in V2

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#190]
- launch mia
- open a project with a.nii et b.nii.
- go to Pipeline Manager
- drag and drop the mia_processes Smooth brick 
- fill in_files parameter with a.nii, then initialise
- sa.nii is now in the Data Browser tab
 - in fact we want b.nii in in_files parameter! Fill in_files parameter with b.nii, then initialise
- sa.nii and sb.nii  are now in databrowser
- no, no, no, in fact we want a.nii in in_files parameter! Fill in_files parameter with a.nii, then initialise, then run

There are now sa.nii and sb.nii in the database. sa.nii has the Bricks tag filled in with the `Exec` and `Exec Time` tag indexing whereas sb.nii does not, which may help the user to know that sb.nii is not synchronised with reality.

We are currently working hard on initialisation and how to solve this type of disorder. This ticket is open to illustrate the mess resulting of multiple initialisations without a run between them in V2. It should be closed when the reflections #181 will have succeeded and when the changes in codes will have been done

**Comment by denisri** [comment]
Confirmed.
The bricks are cleaned when doing another initialization (`sa.nii` doesn't have a brick in its history when the init using `b.nii` is done, and same for `sb.nii` when we re-select `a.nii` as input). We should add something that cleans non-existing files associated with no brick execution history. I can look at that.

**Comment by denisri** [comment]
I have pushed a modif which cleans up orphan non-existing files when re-doing an initialization or using the clean button.
Tell me if it fixes the problem for you.

**Comment by servoz** [comment]
in fact it seems that the populse_mia populse_db2_capsulengine branch is not synchronised with the one in your fork.
On populse/populse_mia the last commit was on Wed May 12.
Can you synchronise the populse_db2_capsulengine populse and denisri branches? Or do you want me to use your fork directly?

**Comment by denisri** [comment]
;)
Totally right, I forgot I had a fork ! My bad, sorry... it's pushed now...

**Comment by servoz** [comment]
Oh yes. Your fix is effective !
I close this ticket !!!!!!
