### ISSUE TITLE
[continuous integration] Unit tests in continuous integration are currently failing

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#195]
For Linux / Mac (travis) and Windows (appveyor)

- For Linux: it seems to be related to the #187 issue as the tests crash when it comes to undo /redo. Fixing #187 should therefore hopefully resolve this part of the ticket.
- For Mac:  the build seems to be stalled, no output is received from a build for 10 minutes.
- For Windows: problem with pip installation of scikit-image (not observed with linux)

**Comment by servoz** [comment]
Unit tests are now working again on the master branch (V2).

A lot of changes have been made for that, with a lot of work on undo/redo, but as the goal was to restart the UT I'm not sure if everything is set for undo/redo. There is a ticket about undo/redo (#187), it is a separate topic and it will be better to come back to this ticket specifically.

There were some necessary changes in capsul for the restart of UT. [I made a PR](https://github.com/populse/capsul/pull/185) for that (until this PR is validated, unit tests still won't work).

So the unit tests work now on a linux build and virtually also on macOS.

There is still a specific error on windows, I will open a new ticket specially for that. 

I will also open a new ticket to find a new solution to do UT on linux since we can't use Travis now without paying!!!

I think we can now close this ticket!

**Comment by denisri** [comment]
Great ! The PR is merged in capsul.

**Comment by servoz** [comment]
nice !
