### ISSUE TITLE
Populse_mia crashes when you click on the 'Filter' button in Pipeline Manager

### ISSUE THREAD

**Issue by montigno** [populse/populse_mia#206]
procedure : launch Populse_mia, go to 'Pipeline Manager', click on 'Filter' button : the software crashes.

**Comment by servoz** [comment]
I can't reproduce this bug.
If I follow this minimum procedure that is:
-  launch Populse_mia
-  go to 'Pipeline Manager'
I don't see a Filter button at this stage !
![Screenshot from 2021-06-28 15-35-46](https://user-images.githubusercontent.com/37933899/123645395-98de6280-d826-11eb-87e1-d64a10a98349.png)

Maybe there is a step missing in the minimal procedure to reproduce the bug?

**Comment by montigno** [comment]
Top right, below the 'Select' button

**Comment by servoz** [comment]
Minimum procedure to reproduce the bug:
- launch mia
- go to `Pipeline Manager`, 
- click on the `Filter` button in the iteration window (above the `Select` button)
- Mia crashes while raising the exception:
 ```
Traceback (most recent call last):
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/iteration_table.py", line 273, in filter_values
    tag_values = self.all_tag_values
AttributeError: 'IterationTable' object has no attribute 'all_tag_values'

```

**Comment by denisri** [comment]
A variable was nor initialized. It should be fixed now.

**Comment by servoz** [comment]
I can do ... U take, I take ?

**Comment by servoz** [comment]
you shoot faster than your shadow ... ok ok you've already done it !!!

**Comment by servoz** [comment]
I have just tested it. This issue is now fixed.
