### ISSUE TITLE
Mia crashes when we click on the "Select" button in the Pipeline Manager, iteration window.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#208]
Minimum procedure to reproduce the bug:
- launch mia
- go to Pipeline Manager,
- click on the `Select` button in the iteration window
- do not select anything, just click on the OK button
- Mia crashes while raising the exception:
```
Traceback (most recent call last):
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/iteration_table.py", line 270, in select_iteration_tag
    self.update_iterated_tag(ui_select.selected_tag)
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/iteration_table.py", line 318, in update_iterated_tag
    self.iterated_tag_label.setText(tag_name + ":")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by denisri** [comment]
Strange, I don't have the same behaviour: I get the popup with "available tags:", "Bricks, Exp Type, FileName, Type". (without any project open)

**Comment by servoz** [comment]
I had forgotten to indicate:
- do not select anything, just click on the OK button ...

I edited the first post for this ...

**Comment by denisri** [comment]
Oh yes this time I see it :)

**Comment by servoz** [comment]
I am looking at this ... please don't shoot this time ... :-)))
