### ISSUE TITLE
Some buttons see their label change

### ISSUE THREAD

**Issue by montigno** [populse/populse_mia#209]
Minimum procedure to reproduce the bug:

 * launch MIA
 * go to Pipeline Manager
 * click on 'SequenceName' button (to the right)
 * a 'main.py' window opens, click on 'ok'
 * the button label disappeared

It makes the same problem with the 'AcquisitioDate' button

**Comment by montigno** [comment]
In the `populse_mia/python/populse_mia/user_interface/pipeline_manager/iteration_table.py` file , at line 303, I think we should add : 

 ' if popUp.selected_tag: ' and indent the next 3 lines

**Comment by servoz** [comment]
sure !
