### ISSUE TITLE
MIA crash when we click on the `Edit CAPSUL config` button

### ISSUE THREAD

**Issue by montigno** [populse/populse_mia#211]
Procedure to reproduce the bug :
 * launch MIA
 * go to 'MIA preferences' in 'File' menu
 * go to pipeline
 * click on `Edit CAPSUL config` button
 * MIA crash:

Error message:
	
	Traceback (most recent call last):
  	File "/home/omontigon/Apps/casa_distro/populse_mia/python/populse_mia/user_interface/pop_ups.py", line 2548, in edit_capsul_config
    	engine.study_config.import_from_dict(sc_dict)
  	File "/casa/host/build/python/soma/controller/controller.py", line 427, in import_from_dict
    	setattr(self, trait_name, value)
  	File "/usr/lib/python3/dist-packages/traits/trait_types.py", line 1493, in validate
    	self.error( object, name, value )
  	File "/usr/lib/python3/dist-packages/traits/trait_handlers.py", line 172, in error
    	value )
	traits.trait_errors.TraitError: The 'matlab_exec' trait of a StudyConfig instance must be a file name, but a value of '' <class 'str'> was specified.

**Comment by servoz** [comment]
I think your configuration is corrupted. 
And it looks like capsul does not support this corruption!

- The easiest way would be to restart from an empty configuration (as at the installation).
- The best would be to understand what happened to get there! 

Two options ! One fast, the other useful to fix this issue!

If you go to File > Mia preferences and click in Edit config button:
There is the possibility to search for characters in the config if you are in Admin mode (fill in the bottom field and click on find button (beware it is possible to write in the config at this level!) the searched string will appear highlighted in red):
What do you get if you search for the matlab string?

**Comment by montigno** [comment]
If I go to File -> MIA preferences, I don't find the 'Edit config' button.
I think I must be in administrator mode, if I check 'Admin mode', I must enter the admin password. Which one is it ?

**Comment by servoz** [comment]
I just sent you the passwd in mp.

**Comment by montigno** [comment]
thanks for the password.

After click on  the 'Edit config' button, I have the config window where I see `matlab_exec: ''` and `use_matlab: false`.

In MIA Preferences, 'Use Matlab' is well unchecked.

**Comment by servoz** [comment]
In File > Mia Preferences > Change configuration, I am very surprised that you have only two occurrences for "matlab" ...

Anyway, please can you delete the whole line with the matlab_exec occurence, then start again mia.
Just to see, please, before doing this deletion can you paste in this ticket :
- the 10 lines before matlab_exec 
- the line with matlab_exec
- the 10 lines after

**Comment by servoz** [comment]
ok I succeed to reproduce the issue.
Just remove the line as I told you before to fix it.
I also push a fix that should avoid this kind of issue.

**Comment by montigno** [comment]
I deleted the line containing matlab_exec and the problem is fixed !
