### ISSUE TITLE
[Iteration enhancement] In Data Browser, the Bricks tag contains n times THE SAME BRICK

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#219]
Observed in the 3 iteration modes [described in the documentation](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#pipeline-iteration).

After initialisation then run also, in Data Browser and for the Bricks tag, an anomaly in the indexing of the database is observed: the Bricks tag contains n times THE SAME BRICK (n equals the number of iterated patients ).

**Comment by LStruber** [comment]
This issue has been resolved as a side effect of commit 80f0460003373a1875879008a8247d6636cff951 related to issue #217
