### ISSUE TITLE
[Iteration enhancement]  we lose the filtration data of the iteration table, if we change tabs and go back again

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#221]
If we use the iteration table, as described in the document for the [Via Input_Filter with the use of the iteration table](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#with-use-of-the-iteration-table) mode :

Before initialisation:

  If we change tabs (e.g. by going to the Data Browser or staying in the Pipeline Manager but opening a new editor or going to another editor and then coming back to the one with the pipeline to iterate) it seems that the data filter in the iteration table is lost.

For example:
  - I prepare an iteration as described in [the documentation](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#with-use-of-the-iteration-table) (exclusion of one patient out of the 3 in the database)
  - I go to the Data Browser then I come back in the Pipeline Manager to the editor with the iteration:
    - in this case there is no more filtration on the patients. 
    - Same observation, staying in the piepline manager, if I change of editor and then go back.

The remedy is to redefine the filter each time we return to a tab, but we would like to be able to keep the data when we change tabs (and this is prone to errors).

**Comment by LStruber** [comment]
In the same line, while the checkbox iterate pipeline is updated between tabs (if I open a tab with an iterated pipeline and another without, switching from one to the other automatically check or uncheck the box), it is not the case for the iteration table parameters.
In my opinion, they should also be "tab-dependent", as we could imagine to iterate over two different parameters in two different tabs.

**Comment by servoz** [comment]
I totally agree!

**Comment by LStruber** [comment]
fix with commit 0665bf2e24e9d416f0da5cd91fa1209fc32bc673
