### ISSUE TITLE
BrainVisa VirtualBox 5.02 Windows : aims python 2 error in Populse_Mia Viewer

### ISSUE THREAD

**Issue by urlub** [populse/populse_mia#224]
**Bug Description**

I've installed  BrainVisa image 5.02 in VirtualBox. 
Then installed Populse_MIA (only populse_mia, mia_processes and mri_conv) and launch it in python3 venv and i get this error when i clic on viewer tab.
Eric told me that we need bv_maker but it's not available in this VirtualMachine

**Generated error**
```
anatomist_2 viewer is not available or not working ...!
Traceback:
  File "/home/brainvisa/DEV/populse/populse_mia/python/populse_mia/user_interface/data_viewer/data_viewer_tab.py", line 135, in load_viewer
    '%s.%s' % (__name__.rsplit('.', 1)[0], viewer_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/brainvisa/DEV/populse/populse_mia/python/populse_mia/user_interface/data_viewer/anatomist_2/__init__.py", line 2, in <module>
    from .mia_anatomist import MiaViewer
  File "/home/brainvisa/DEV/populse/populse_mia/python/populse_mia/user_interface/data_viewer/anatomist_2/mia_anatomist.py", line 21, in <module>
    import anatomist.direct.api as ana
  File "/casa/install/python/anatomist/direct/api.py", line 60, in <module>
    from anatomist import cpp
  File "/casa/install/python/anatomist/cpp/__init__.py", line 172, in <module>
    from soma import aims
  File "/casa/install/python/soma/aims/__init__.py", line 148, in <module>
    exc
  File "<string>", line 3, in raise_from
ImportError: version mismatch: you are running Python 3.6.9 but the soma.aims module was likely compiled for Python 2.

anatomist viewer is not available or not working ...!
Traceback:
  File "/home/brainvisa/DEV/populse/populse_mia/python/populse_mia/user_interface/data_viewer/data_viewer_tab.py", line 135, in load_viewer
    '%s.%s' % (__name__.rsplit('.', 1)[0], viewer_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/brainvisa/DEV/populse/populse_mia/python/populse_mia/user_interface/data_viewer/anatomist/__init__.py", line 2, in <module>
    from .mia_anatomist import MiaViewer
  File "/home/brainvisa/DEV/populse/populse_mia/python/populse_mia/user_interface/data_viewer/anatomist/mia_anatomist.py", line 11, in <module>
    from anatomist.simpleviewer.anasimpleviewer import AnaSimpleViewer
  File "/casa/install/python/anatomist/simpleviewer/anasimpleviewer.py", line 37, in <module>
    import anatomist.direct.api as ana
  File "/casa/install/python/anatomist/direct/api.py", line 60, in <module>
    from anatomist import cpp
  File "/casa/install/python/anatomist/cpp/__init__.py", line 172, in <module>
    from soma import aims
  File "/casa/install/python/soma/aims/__init__.py", line 148, in <module>
    exc
  File "<string>", line 3, in raise_from
ImportError: version mismatch: you are running Python 3.6.9 but the soma.aims module was likely compiled for Python 2.

```

**Expected behavior:**
When we clic on viewer tab in populse_mia, we have access to anatomist viewer

**Desktop:**
 - OS: VirtualBox 6.1.26 on Windows 10
 - Populse_MIA version 2.0.0-dev+265707cc

**Comment by denisri** [comment]
BrainVisa 5.0.2 binary distribution is built for Python 2, it cannot be used with populse_mia. Future releases 5.1 will use Python 3, but for now, to work correctly you need a developer build.

**Comment by servoz** [comment]
So I guess it's the same issue as the #216 ticket.
As I asked in this ticket (#216), while the work on the developer build is in progress, could we have some help to do the modifications by hand on our side so that we don't get stuck waiting for the right build?

**Comment by denisri** [comment]
A few things to make it work (not sure this is complete):
```
mkdir /casa/host/src
mkdir /casa/host/build
mkdir /casa/host/conf
cat << EOF > /casa/host/svn.secret
SVN_USERNAME=brainvisa
SVN_PASSWORD=Soma2009
EOF
cat << EOF /casa/host/conf/bv_maker.cfg
[ source $CASA_SRC ]
update_git_remotes = ON
brainvisa opensource master

[ build $CASA_BUILD ]
default_steps = configure build doc
make_options = -j4
cmake_options = -DPYTHON_EXECUTABLE=/usr/bin/python3
build_type = Release
packaging_thirdparty = OFF
clean_config = ON
clean_build = ON
brainvisa opensource master $CASA_SRC
EOF
```
then add in your `~/.bashrc` (in the VM user account):
```
. /casa/dev-environment.sh
export PATH="$PATH":/casa/bootstrap/brainvisa-cmake/bin
. /casa/bootstrap/brainvisa-cmake/etc/bash_completion.d/bv_maker-completion.bash
```
After sourcing the `~/.bashrc` or opening a new shell/terminal, you should be able to use `bv_maker`.
The first use of bv_maker will probably end with an error because the preinstalled version is outdated and things have changed on the server, but it's enough to get the new sources. You can then run (once):
```/casa/host/build/bin/bv_maker configure build
```
Then it will update, and the next times (after reopening a shell or sourcing /casa/dev-environment.sh) bv_maker will be called from the build tree:
```
which bv_maker
/casa/host/build/bin/bv_maker
```
All this should be configured automatically when we fix and rebuild the vbox dev images.

**Comment by servoz** [comment]
cool ! Thanks @denisri !
I can't wait to hear what @urlub  will say after trying this!

**Comment by urlub** [comment]
> 
> 
> BrainVisa 5.0.2 binary distribution is built for Python 2, it cannot be used with populse_mia. Future releases 5.1 will use Python 3, but for now, to work correctly you need a developer build.

Ok with different documentations from brainvisa and https://github.com/populse/populse_mia/blob/master/developer_doc/UsingVirtualisation.md,  i had started to use Windows 10 wsl2, ubuntu-18.04, singularity 3.8, casa-dev-5.0-4.sif, python3 and Qt5 compilation options and bv_maker works. Then get populse_mia, mri_conv and mia_processes and finish with 
bv python populse_mia/main.py and ....... IT WORKS with anatomist and ana2 Viewer ! Great !
I must test my notes before publish a documentation. I'll also do the same for ubuntu20 wsl2

**Comment by urlub** [comment]
> 
> 
> A few things to make it work (not sure this is complete):
> 
> ```
> mkdir /casa/host/src
> mkdir /casa/host/build
> mkdir /casa/host/conf
> cat << EOF > /casa/host/svn.secret
> SVN_USERNAME=brainvisa
> ```
> . . . . . . . . .
> All this should be configured automatically when we fix and rebuild the vbox dev images.

Ok, i'll test this in VirtualBox

**Comment by urlub** [comment]
> A few things to make it work (not sure this is complete):
> 
> ```
> mkdir /casa/host/src
> mkdir /casa/host/build
> mkdir /casa/host/conf
> cat << EOF > /casa/host/svn.secret
> SVN_USERNAME=brainvisa
> SVN_PASSWORD=Soma2009
> EOF
> cat << EOF /casa/host/conf/bv_maker.cfg
> [ source $CASA_SRC ]
> update_git_remotes = ON
> brainvisa opensource master
> 
> [ build $CASA_BUILD ]
> default_steps = configure build doc
> make_options = -j4
> cmake_options = -DPYTHON_EXECUTABLE=/usr/bin/python3
> build_type = Release
> packaging_thirdparty = OFF
> clean_config = ON
> clean_build = ON
> brainvisa opensource master $CASA_SRC
> EOF
> ```
> 
> then add in your `~/.bashrc` (in the VM user account):
> 
> ```
> . /casa/dev-environment.sh
> export PATH="$PATH":/casa/bootstrap/brainvisa-cmake/bin
> . /casa/bootstrap/brainvisa-cmake/etc/bash_completion.d/bv_maker-completion.bash
> ```
> 
> After sourcing the `~/.bashrc` or opening a new shell/terminal, you should be able to use `bv_maker`.
> The first use of bv_maker will probably end with an error because the preinstalled version is outdated and things have changed on the server, but it's enough to get the new sources. You can then run (once):
> 
> Then it will update, and the next times (after reopening a shell or sourcing /casa/dev-environment.sh) bv_maker will be called from the build tree:
> 
> ```
> which bv_maker
> /casa/host/build/bin/bv_maker
> ```
> 
> All this should be configured automatically when we fix and rebuild the vbox dev images.

i'm not found /casa/dev-environment.sh 
none /casa/bootstrap/brainvisa-cmake/etc/bash_completion.d/bv_maker-completion.bash

i found only this in the virtual box brainvisa
 /casa/install/share/casa-distro-3.0/docker/casa-dev/ubuntu-18.04/dev-environment.sh
./casa/install/etc/bash_completion.d/bv_maker-completion.bash

and also there is any path to brainvisa-cmake/bin

**Comment by denisri** [comment]
You have probably downloaded the user image (brainvisa-5.0.2), not the developer image (casa-dev-5.0-1).

**Comment by urlub** [comment]
yes you right, sorry i don't see in your documentation this one.
just correct a little mistake (<)  i forgot to mention : 
>
>cat << EOF /casa/host/conf/bv_maker.cfg
>
cat << EOF > /casa/host/conf/bv_maker.cfg

**Comment by denisri** [comment]
Thanks, I have edited and fixed the message.

**Comment by servoz** [comment]
I guess the issues for this this ticket are now fixed, right?
Please, @urlub , if that's the case, can you close that ticket?

**Comment by urlub** [comment]
I've done many installations and i confirm it works fine with the brainvisa developer image (casa-dev-5.0-4 and 5) with wsl2 on windows.
I'd update the https://github.com/populse/populse_mia/blob/master/developer_doc/UsingVirtualisation.md documentations,

**Comment by urlub** [comment]
I closed this solved issue
