### ISSUE TITLE
[general need] Mia loses the name of the brick in case of a calculation launch error (e.g. a pipeline without input parameters)

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#258]
The minimum steps to reproduce :
- Open Mia
- Open a project
- In the pipeline manager, drag and drop the SPM Smooth brick from mia_processes, into the editor
- Click on the "Run pipeline" button (this is an error as we have not yet defined the input parameters, but errors should be handled in Mia)
- A pop-up window opens indicating that a mandatory parameter for the pipeline is missing (note that the Smooth brick/process is called main, which is not appropriate)
![Screenshot from 2022-03-10 10-34-53](https://user-images.githubusercontent.com/37933899/157633433-f2821d35-7163-418c-bec2-4eed9dbceb3c.png)
=> Except for the problem of the name of the brick, the case is well managed now (following the [previous opened ticket on this subject](https://github.com/populse/capsul/issues/199)).

If we now want to get things right:
- Right click in the brick and choose "Export all unconnected records" (**all nodes turn blue**, why ?)
- Select a in_files parameter using the Filter button, in the controller
- Click on the "Run pipeline" button
- Calculation runs correctly, **but**:

We see on the status bar: Pipeline "NoName" has been correctly run
We see on the stdout:
![issue1](https://user-images.githubusercontent.com/37933899/157635884-d7287c5e-4995-4a78-baf7-f76064a770fa.png)
And we see in DataBrowser for the Bricks tag (this is the most important problem, as we lose the data history in this case) :
![issue2](https://user-images.githubusercontent.com/37933899/157636306-d06f8a60-82cf-443f-a703-f6066e28918e.png)

**EDIT:** If we hit the `main` button, mia crashs with this exception:

```
Traceback (most recent call last):
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 2177, in show_brick_history
    self.data_browser.main_window)
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pop_ups.py", line 5034, in __init__
    self.node_selected(full_brick_name[0], pipeline.nodes[full_brick_name[0]])
KeyError: 'main'

```

**Comment by servoz** [comment]
The "main" name comes from the [capsul.pipeline.pipeline_workflow.workflow_from_pipeline() method](https://github.com/populse/capsul/blob/master/capsul/pipeline/pipeline_workflow.py#L1549) when the pipeline is in fact a single process.

Maybe I'm missing something (maybe there's a reason for using 'main' as the name in all cases?) but as this is a pipeline with a single process, the node must take the name of the class + '_1'.

So, I think this line should be:
`new_pipeline.add_process(pipeline.name.lower() + "_1", pipeline)`

@denisri, what do you think?
If you don't see a side effect I'm missing, I can make the change directly in capsul.

**Comment by denisri** [comment]
No problem, it's fine... it was just a bit of code done too quickly.

**Comment by servoz** [comment]
Done.
