### ISSUE TITLE
[Run step] Run and garbage collect buttons should be disabled when a pipeline is running

### ISSUE THREAD

**Issue by LStruber** [populse/populse_mia#259]
Currently, when a pipeline is running, Run button and Garbage collect button are enabled.

1. Regarding run button ![image](https://user-images.githubusercontent.com/86590799/158206340-354ffe79-341e-4904-9bde-be4f20f61108.png)
If I click again on run button, the pipeline is re-run and two concurrent run instances are launched (with two progress bar, see image below). Moreover, at the end of the second run, MIA crashed with exception :
```
Traceback (most recent call last):
  File "/home/lucas/populse_dev/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1180, in finish_execution
    status = self.progress.worker.status
AttributeError: 'PipelineManagerTab' object has no attribute 'progress'
```
![image](https://user-images.githubusercontent.com/86590799/158206146-c27c6188-52f4-4ed2-ac08-a711eecd9169.png)

2. Regarding garbage collect button ![image](https://user-images.githubusercontent.com/86590799/158206457-97fc3d32-35ea-4603-84db-0bf62bdeb390.png)
If it clicked while the pipeline is running, pipeline execution suceed but the file entry is not created in the database (while it is saved on disk !)

As using these buttons during run is not an expected behavior, I think that as suggested in the title, the safe solution is to disable both button while a pipeline is running.

**Comment by denisri** [comment]
Yes, perfectly true. The run button used to be disabled during run, and I think its disabling has disapeared when the "init" step was merged into the "run" step - f1e29bfd7a233aa9d4756c599e2dbb2b04a03d86 if I'm correct. For the garbage collect, I don't remember but it's possible it has never been disabled. However its disabling should be the same as for the run button.
I guess one day we might want to run concurrently several pipelines (with different parameters probably, possibly from different pipeline manager tabs) but this is not taken into account today.
