### ISSUE TITLE
Modules are added multiple times in UserProcesses/__init.py__

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#26]
When a pipeline is saved, a new import statement is added to \_\_init.py\_\_ each time, regardless whether it already exists or not. This may be mostly a cosmetic issue, but I think we should aim for a clean file here, with one line for every user process present.

**Comment by dhrbn** [comment]
You are right! In the updateProcessLibrary() method of the PipelineManagerTab, we should first read the __init__.py file of the User_processes package and check if the pattern "from .module_name import class_name" is not already in the file.
