### ISSUE TITLE
[DataBrowser] Boolean list, Time list and Datetime list types are not well managed

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#276]
Let's say we start from the following project:

![Screenshot from 2022-06-13 17-54-12](https://user-images.githubusercontent.com/37933899/173395642-ccc1bb5c-0f0f-4adb-b6e9-6f665b2f2a16.png)

- Boolean list type:
------------------------
If we want to change the value of the "boolean_list" tag (boolean_list type), the result is an empty list:
![Screenshot from 2022-06-13 17-57-11](https://user-images.githubusercontent.com/37933899/173395722-21c582a5-e274-4f1c-880e-841b7733b3fc.png)

 We get the same result if we don't change the value but just hit the OK button in the popup allowing the value change:
![Screenshot from 2022-06-13 17-58-57](https://user-images.githubusercontent.com/37933899/173395796-46dcfcae-06e1-4f4e-b7d3-f67ed14e37a5.png)

- Datetime list and Time list types:
--------------------------------------------- 

- Datetime list type tag:

For the datetime_list tag, if we change the value or, if, without changing the values, we just click on the OK button of the popup allowing to change the value:
![Screenshot from 2022-06-13 18-08-11](https://user-images.githubusercontent.com/37933899/173397156-94daaca9-2a91-47be-98fc-3a3860f6131d.png)

 mia crash with the following exception:
```
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/modify_table.py", line 185, in update_table_values
    subvalue = datetime.strptime(text, format)
  File "/usr/lib64/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib64/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: :57.605529

```
- Time list type tag:

Same thing with the time_list tag (time_list type):

```
Traceback (most recent call last):
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/modify_table.py", line 189, in update_table_values
    subvalue = datetime.strptime(text, format).time()
  File "/usr/lib64/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib64/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: :14.814666

```

**Comment by YannNdr** [comment]
Closed by 6bf69f9
