### ISSUE TITLE
Crash when trying to save project without creating one first

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#3]
When MIA opens, no project is active. When the inexperienced user now tries to save the current project, MIA crashes. This crash is independent of the directory chosen, and whether it exists already or not.

```
Error message:
excepthook
clean up done
Traceback (most recent call last):
  File "/home/warnking/code/fmri_processing/python/populse/populse_sandbox/python/populse_mia/src/modules/MainWindow/Main_Window.py", line 364, in save_project_as
    os.makedirs(self.exPopup.relative_path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '../../../../../../../../../../../data/warnking/irm/methodo/populse/181009_test'

```

How to reproduce:
1. Start MIA
1. File > Save As
1. Specify an existing or non-existing directory

→ crash

**Comment by JanWP** [comment]
I should add that an error is flagged by MIA before opening the file selection dialog, but this error is not explicit. It complains about a non-existing directory. Expected behavior is an error indicating to the user that he or she needs to open or create a project first, and to not open the file selection dialog.

**Comment by servoz** [comment]
[I can't reproduce this bug !](https://mycore.core-cloud.net/index.php/s/xh3Tz37ClD3BjYH) ...

the relative path in the message raised with the FileExistsError class let's me confused ...	at first glance too much '../..' (but could be not the problem ...) To follow

**Comment by servoz** [comment]
Ok I see !!! This exception is raised when the user wants to save the project to a location other than the one planned (in populse_mia/processes). Currently the user can't know this because the documentation is not yet available!
We  can discuss later if the process directory is only an option.

**Comment by JanWP** [comment]
Saving to a non-default location works fine, if a new project is created first. I think, keeping code and data in different locations (in my case: on different partitions) is very common. I thought, specifying the location of the database was the purpose of the file selection dialog.

**Comment by servoz** [comment]
I totally agree for keeping code and data in different locations. In fact we plane to change it later, at the deployment time in pypi ! (we just get populse_mia out of the sandbox today and now everything is in the same directory! Of course, the modules must at least go with the python modules, etc.). To follow ...

**Comment by JanWP** [comment]
Side note: Github mistakenly links a recent pull request to this issue, which references the merge of development here into my fork JanWP/populse_mia#3.

On topic: This issue is more severe than initially indicated. 
"Save as..." on a project appears to be broken on my system. This comes from the fact that the `QFileDialog.ShowDirsOnly` option of the `QFileDialog` widget does not support specifying non-existing directories on my system. If I navigate to an existing directory and then type in the name of a non-existing one, the return value only contains the path of the existing parent directory. `Ui_Dialog_Save_Project_As.return_value` subsequently [tests for existence](https://github.com/populse/populse_mia/blob/61bb5a80ee9eff9d91ceb8733e3ed35fb635f743/python/populse_mia/src/modules/PopUps/Ui_Dialog_Save_Project_As.py#L65) of the directory and only emits the `self.signal_saved_project` signal if the path points to a directory which does _not_ exist.
Further down the pipeline still, `MainWindow.save_project_as` [tries to create the directory without any prior check](https://github.com/populse/populse_mia/blob/61bb5a80ee9eff9d91ceb8733e3ed35fb635f743/python/populse_mia/src/modules/MainWindow/Main_Window.py#L404) and `os.makedirs` throws an exception.
