### ISSUE TITLE
[Initialization step] Requirements management is suboptimal

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#300]
It seems that the requirements management is currently a mixture of elements from V1 and V2, which in some cases leads to a result that is at best imperfect, at worst wrong.

We would like to have a message at initialisation time, which would tell the user exactly which of the requirements is wrong, in a way that is simple and easy to understand for the average user.

**Comment by manuegrx** [comment]
Side effect of this issue : 

When using alone a brick with self.requirement = [] there is an issue during pipeline initialization.
A windows appears with the following message :
![message](https://user-images.githubusercontent.com/47973414/233334217-3b211a81-e4c3-4b13-b557-537defd96afa.png)

However if we used this brick in a pipeline there is no pipeline initialization issue

For example brick preprocess.others.ConformeImage --> intialization issue when using the brick alone and okay when brick is used in Anat_mriqc pipeline.

**Comment by servoz** [comment]
The [issue#300](https://github.com/populse/populse_mia/tree/issue%23300) branch does now the job.
I'm waiting to merge it with master until the [PR at capsul ](https://github.com/populse/capsul/pull/281) is accepted and the unit test problems caused by these changes are corrected.
Then I will close this ticket.

**Comment by servoz** [comment]
Done!
