### ISSUE TITLE
Tests during pipeline initialisation (linked with #110 and #151)

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#34]
Go further to check if a pipeline is runnable during its initialisation.
Ex: In the nipype smooth brick, does the in_file parameter correspond to a scan referenced in the data browser ? etc ...
See the init_pipeline() method in populse_mia.pipeline_manager.pipeline_manager_tab.PipelineManagerTab

**Comment by servoz** [comment]
I am reopening this issue because it seems that it was closed 2 days ago, as a side effect of the rewrite of the history, which I made in order to delete from the history the large files now followed by git-fs.
The first investigation I conducted seems to indicate that following this operation, some issues have been closed (which I will reopen after some checks). The integrity of the populse_mia project does not seems to have changed (I think the SHA-1 of the commits were changed during the operations, that could explain the side effect observed!)

**Comment by M40V** [comment]
Currently if there's a configuration issue with Matlab or SPM, we show the user an alert box but we do not stop the initialization.
We should be able able to stop the initialization at given moments and clear the generated data when something is wrong.

**Comment by M40V** [comment]
For the iteration, instead of running the pipeline after each initialization, we should initialize for all iteration, save the generated data in a dictionary and then feed them one by one to run the pipeline.

**Comment by servoz** [comment]
Currently, if we run the pipeline without having initialised it previously, in first hand it is possible and in second hand mia crash (mainly because mandatory parameters were not created by the initialisation step). Therefore, the pipeline should not be able to be run (shaded "run" button) until the initialisation has been successfully completed.

**Comment by servoz** [comment]
This is now fixed in V1
