### ISSUE TITLE
Non coherent message when stopping an export to MIA

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#35]
Currently, if an export from the MRIconverter to MIA is cancelled  (ex. in case of already existing scan in the MIA data browser, if we push the "No" button on the Warning popup), the log message popup display the message: Export completed with success ... Do not really know yet where comes from the problem ... to discuss !!!

**Comment by dhrbn** [comment]
I have just tested what you said. I don't really think that this is a big problem. The "Export completed with success" pop-up seems to be displayed just before exiting the MRIFileManager, in any case. So maybe the text of this pop-up should just have to be change depending on if they are exported files or not. Anyway, this has to be discussed with @montigno !

**Comment by servoz** [comment]
I also think it is not a big problem, it is rather for displaying a consistent exit message from the MRIFileManage. I believe that this exit message have to be dependent of the real context. In this case an message like "No exported data" will be better. So I propose to use an if statement that display an  contextual exit message rather that a general message that do not fit to the reality in some cases

**Comment by dhrbn** [comment]
This problem has been solved in the last version of the MRI File Manager.
