### ISSUE TITLE
Change the AppVeyor account

### ISSUE THREAD

**Issue by dhrbn** [populse/populse_mia#37]
Currently, the CI with AppVeyor is currently run with my personal account (https://ci.appveyor.com/project/dhrbn/populse-mia). But it should be better to use populse's account (https://ci.appveyor.com/project/populse/populse-mia) which has not been updated since a long time. I think I couldn't use it when I've created the populse_mia repository because I hadn't the right to do it.

Do not forget to change the address of the AppVeyor badge in populse_mia's README.md

**Comment by servoz** [comment]
ok ! May be it's for this reason that the AppVeyor build badge, in populse_mia's README, is currently failing. I will see it ASAP

**Comment by dhrbn** [comment]
I've just changed it and it's currently passing!

**Comment by servoz** [comment]
excellent !
