### ISSUE TITLE
Missing java libraries in included MRI file manager

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#4]
The version of the MRI file manager that is packaged with MIA is missing the following libraries:

- bioformats_package.jar
- pixelmed.jar
- pixelmed_imageio.jar

This renders display and conversion of DICOM data impossible. The libraries are included in the latest version of the MRI File manager available [here](https://gricad-gitlab.univ-grenoble-alpes.fr/irmdataprocess/MRI_File_Manager/raw/master/download/MRIFileManager.zip).

**Comment by dhrbn** [comment]
https://github.com/populse/populse_mia/commit/4fb1eca463d85c664bb8b168168dd57b6ae3e0ad closed this.
