### ISSUE TITLE
Change the location of populse_mia_install repository, linked with #47

### ISSUE THREAD

**Issue by dhrbn** [populse/populse_mia#43]
To test the deployment and the installation of Populse_MIA, I've created a "populse_mia_install" repository on my profile (cf. https://github.com/dhrbn/populse_mia_install/). It contains the script and widget of Populse_MIA's install. In the documentation (cf. https://populse.github.io/populse_mia/html/installation/user_installation.html), the download link is directed to my "populse_mia_install" repository.

Because the first deployment is imminent and I am leaving soon, I think we should move this repository to the populse project or to a profile of another person (@servoz for instance?). Tell me what you think.

**Comment by servoz** [comment]
I think the best location could be in the populse project. If it's not too heavy, in https://github.com/populse/populse_mia (for not  increase dramatically the number of repositories linked to another repository in populse ) ?

**Comment by dhrbn** [comment]
The only way I've found to download code is to download an entire git repository, so we cannot place these files in populse_mia, unless someone knows how to download only some parts of a repository.

**Comment by servoz** [comment]
So. Ok to put in https://github.com/servoz. We will see latter if it's possible to move it to populse_mia ...

**Comment by dhrbn** [comment]
Ok! I'm currently working to improve the upgrade of capsul and soma on windows, maybe we should do it this afternoon.

**Comment by sapetnioc** [comment]
AFAIK it is not possible to download only some files of a repository with
git commands. If I am wrong I would like to know how to do it. The only
thing I found is to do 'git clone --depth 1' to limit download size. On the
other hand, on GitHub, it is possible to have HTTPS links on raw files.
They also expose the repositories with a Subersion API wich allow to list
directories and download files. Therefore, git is not really an option but
GitHub specific protocols or API can do the job.

**Comment by servoz** [comment]
Sure ! I have just created a populse_mia_install repository @servoz. We will see that this afternoon !

**Comment by servoz** [comment]
thanks a lot @sapetnioc !!! @dhrbn leaves now very soon and because we want to make the first symbolic deployement before his leaving (and there is still so much imperfect points to fix for now !!!), we will use the quick and dirty solution in a @servoz repository. But for the next versions, we will explore more clean methods, and, for this, we keep in mind your informations !

**Comment by servoz** [comment]
I reopen this issue to keep in mind the ideas of @sapetnioc concerning the GitHub specific protocols or API to do the job.

**Comment by servoz** [comment]
We are moving towards the use of virtualisation. This ticket is therefore obsolete
