### ISSUE TITLE
Crash when creating the first user pipeline

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#52]
In a fresh user installation, performed according to the documentation, the file \_\_init\_\_.py in the User_processes directory is missing. This makes Populse_MIA crash when saving a user pipeline. It does not matter, if the pipeline manager actually contains a pipeline to save or is empty, Populse_MIA crashes either way.

**Generated error**
```
(pp_populse_mia) me@my_computer:~$ python3 -m populse_mia
excepthook
clean up done
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.6/site-packages/populse_mia/pipeline_manager/pipeline_manager_tab.py", line 626, in updateProcessLibrary
    file = open(init_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/.populse_mia/populse_mia/processes/User_processes/__init__.py'
```

**To Reproduce**
1. Perform a fresh install of populse_mia
2. Run `python3 -m populse_mia`
3. Click on the 'Pipeline Manager' tab
4. In the 'Pipeline' drop-down menu, click 'Save pipeline as'
5. Enter any name in the 'File name' field
6. Click 'Save'

**Expected behavior**
The pipeline is saved.

**Desktop:**
 - OS: Ubuntu 18.04
 - Python: 3.6
 - Populse_MIA: 1.0.1

**Comment by servoz** [comment]
This bug is now (hopefully) fixed. Please let us know...
