### ISSUE TITLE
Warning when clicking on "directories" used to file the bricks in the pipeline library

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#64]
**Expected behavior**
No warning message.

**Actual behavior**
Currently, when we click on a "directory" used to file the bricks in the pipeline library, some give (not all) the following message, in the shell used to open mia:
`
Invalid process_or_id argument. Got '<module 'nipype.interfaces' from '/usr/local/lib/python3.6/site-packages/nipype/interfaces/__init__.py'>' and expect a Process instance/string description or an Interface instance/string description
`

Not yet taking the time to fully understand what is happening, but this behaviour does not seems to be observed for all "directories". The first attempt seems to indicate that with, for exemple, these "directories":
:arrow_down_small: nipype
&nbsp; &nbsp; :arrow_down_small: interfaces
&nbsp; &nbsp; &nbsp; &nbsp; :arrow_down_small: spm
&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; Smooth

- Clicking on :arrow_down_small: nipype
  - gives no warning message

- Clicking on : &nbsp; &nbsp; :arrow_down_small: interfaces:
  - gives:
     - `
Invalid process_or_id argument. Got '<module 'nipype.interfaces' from '/usr/local/lib/python3.6/site-packages/nipype/interfaces/__init__.py'>' and expect a Process instance/string description or an Interface instance/string description
`
- Clicking on : &nbsp; &nbsp; &nbsp; &nbsp; :arrow_down_small: spm:
  -  gives no warning message

**Comment by servoz** [comment]
Edit: The last test performed seems to indicate that this warning is observed on all subdirectories (except for "nipype", the warning is observed for "interfaces" and "spm", unlike what I wrote before...)

**Comment by M40V** [comment]
This warning comes from the method __get_process_instance()_ of capacul/study_config/process_instance.py.
We see a warning when a brick cannot be created from the element that was clicked on.

**Comment by denisri** [comment]
Actually 'module 'nipype.interfaces' is a module, not a process or a nipype Interface class/instance, so maybe get_process_instance() is called with an incorrect argument ?

**Comment by M40V** [comment]
This is it, we never check if it is a module or a process before calling get_process_instance() in the find_process method of the pipeline_manager_tab. I'll commit a fix now.
