### ISSUE TITLE
Import folder for Siemens DICOM

### ISSUE THREAD

**Issue by jipijo** [populse/populse_mia#65]
**Expected behavior**
From "MRI File Manager", I want to import Siemens Dicom files from any folder.

**Actual behavior**
When I want to import Dicom files from the patient folder (ex: Patient Name folder), no dicom was found.
I need to go inside and choose the next folder to import the Dicom files (ex: Exam Name Folder).
If I go further in the next folder and choose one sequence folder (ex 3DT1), no Dicom was found.

**Screenshots**
>Patient Name Folder 
--->Exam Name Folder
-------->Ses 1 Name Folder ex: 3DT1
--------------->image01.IMA, image02.IMA, ect.
-------->Ses 2 Name Folder ex: EPI
--------------->image01.IMA, image02.IMA, ect.
**Additional context**

Johan

**Comment by montigno** [comment]
Close issue without changes to the source code
