### ISSUE TITLE
The CI is currently "failing" and "error"

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#7]
https://travis-ci.org/populse/populse_mia
https://ci.appveyor.com/project/populse/populse-mia

**Comment by dhrbn** [comment]
I've just modified the .travis.yml file to update soma-base with SVN (cf. https://travis-ci.org/populse/populse_mia/builds/441723655?utm_source=github_status&utm_medium=notification and https://github.com/populse/populse_mia/commit/86024d9c619263063e831b3b1b89201e81b4fe74). The tests are passing for Linux and MacOS.

**Comment by dhrbn** [comment]
Reminder: the CI is still not working for Windows

**Comment by dhrbn** [comment]
Now that soma-base is on GitHub, we can clone it for AppVeyor (cf. https://github.com/populse/populse_mia/commit/de3eb03e6788a46d81e3f0d6dcc61ab6dea5cc1b). All the tests have passed for this last commit. 

I do not close this issue because we still encounter some erratic problems with PyQt.

**Comment by dhrbn** [comment]
https://github.com/populse/populse_mia/commit/0b6abda6d6c1a75b2ea31fdf0b9bf2c637ce5c8c#diff-d3df0ea96594c89f50e16f3ed3f00881 seems to have resolved the erratic bugs that we were facing with PyQt5 (now that we cleanly instantiate and exit the application). If I do not see any of these problems in the next few days I will close this issue
