### ISSUE TITLE
There is no management of the __init__.py file when deleting a pipeline in File > Package Library Manager.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#71]
Currently, using the Remove package button in the Package library manager, the given pipeline is deleted from the current library tree structure and the process_config.yml file. But not in the corresponding \__init__.py file ... This means that at  the next time mia starts, it tries to load the pipeline again. I am not making a script change at the moment, although it seems to me that this would be a desirable change, because I think it is not a minor change and it requires a  overall thinking first (and this change can be not so easy to do  ...).
Note: [This management is currently done. only when adding a package, and only for the  User_processes library.](https://github.com/populse/populse_mia/blob/master/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L1334)

**Comment by M40V** [comment]
When the user remove a package, it will create a display where the user will the package that will be removed. The user can cancel the removal of each package that appear in this display.
When the user click on the "Save changes" button, we will update the __init__.py and delete the package directory. There will be a popup for confirmation for each package unless the user click on a button "Yes to all".
After each deletion, we will check the paths to see if there's any package in each paths and remove the empty paths from process_config.yml.

**Comment by servoz** [comment]
First test......
- mia crash when we delete a package, then reset the deleted package.
- 

possible enhancement:
Since the authorisations are different depending on the user, it would be interesting to have "developer mode" or clinical mode" with the title of the window (for example  between brackets and in italics)
