### ISSUE TITLE
RuntimeWarning raised when handling NaN values.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#73]
ex. 
 - [/usr/local/lib64/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/usr/local/lib64/python3.6/site-packages/numpy/core/_methods.py:153: RuntimeWarning: invalid value encountered in reduce
  umr_maximum(a, axis, None, out, keepdims),](https://stackoverflow.com/questions/49013049/runtimewarning-invalid-value-encountered-in-reduce)
with a spm realigned scan
- [/home/econdami/Git_Projects/populse_mia/python/populse_mia/data_browser/mini_viewer.py:773: RuntimeWarning: invalid value encountered in true_divide
  / self.im_2D[idx].ptp() * 255.0)](https://stackoverflow.com/questions/14861891/runtimewarning-invalid-value-encountered-in-divide)
with c1_, c2_, c3 segmented images

It seems this is coming from running matrices with NaN or inf values.

It may be considered to 'clean' the matrices when using mini viewer ... Can be not easy to do (I do not really thought about how to do yet !)

**Comment by servoz** [comment]
* For the realign case (first point):
The latest tests suggest that with the update of numpy and scikit-image (currently numpy==1.17.0 and scikit-image==0.15.0) the RuntimeWarning are no longer observed (/usr/local/lib64/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduction
return umr_minimum (a, axis, None, out, keepdims, initial) etc...) when we click (on the dataBrowser) on the rewritten image after realignment (with the prefix r, in the case of a realign with write).
However, the display of this image remains invisible (and this is the main problem) in the miniviewer (always a black image for all slices and dynamics), while the image is valid as indicated by mricron. The miniviewer may not be able to manage the matrix (NaN ?) without triggering a runtimeWarning ? (which would be desirable in this case!)

* For the segment (second point):
The update of numpy and scikit-image does not change the RuntimeWarning (/home/econdami/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/mini_viewer.py:413: RuntimeWarning: invalid value encountered in true_divide
  / self.im_2D[idx].ptp() * 255.0) etc ...). On the other hand, contrary to the first point, the display exists in the miniviewer.

**Comment by JanWP** [comment]
Regarding point 1, I do not think that a run time warning for all-nan images would be useful. This occurs for some (generally outer) slices in the course of normal image processing. Since there is no data, the image should just remain blank. I will submit a pull request to fix the issue of image size for all-nan images created by #116.

**Comment by servoz** [comment]
Since 2e48066e, the second point of this ticket seems to have been fixed.

However, concerning the first point, if it is now possible to observe the image, it seems to remain a display problem with the slice 1 and and 53 (and for all dynamics) [the ralej170316_test24042018-IRM_Fonct._+_perfusion-2016-03-17_08-34-34-44-04-01-BOLD_CVR_7_53sl_ModeratePNS_SENSE-FEEPI-00-12-12.000. nii in this project ###  I've been fighting with the cnrs clouds for an hour now so I'll give up and I will do an edit if necessary, when the cnrs clouds will be up!, to share the project I'm talking about!).

So I leave this ticket opened for now.

Concerning the run time warning, I think that a (too) verbose terminal (which looks at the messages in the terminal except the developers?) is never undesirable !!!! But it will be not a too big problem for me if we do not display this run time warning ...
