### ISSUE TITLE
Use qt stylesheets to propose multiple themes to the user

### ISSUE THREAD

**Issue by M40V** [populse/populse_mia#74]
**Expected behavior**
A dropdown list in the Appearance tab of the Mia preferences pop-up with a choice of multiple themes.
Like this [dark theme](https://github.com/ColinDuquesnoy/QDarkStyleSheet) for example.

**Screenshots**
![mia_dark](https://user-images.githubusercontent.com/14822018/55804066-eb16fa00-5adb-11e9-96da-63a6b871b844.png)
![mia_dark2](https://user-images.githubusercontent.com/14822018/55804083-ece0bd80-5adb-11e9-813f-9f2dd7308ec7.png)

**Comment by servoz** [comment]
There are so many other tickets still open that are more important than this one and having been open since almost a year without action, I propose to close this issue.
