### ISSUE TITLE
Color of the disabled pipeline

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#75]
I feel that the color of the deactivated pipeline (in the pipeline manager editor) is too dark. It's not an aesthetic consideration, it's just that the current color makes it difficult to read the plug names! This is not a priority improvement, but I think it will be an improvement that must be taken into account.

**Comment by M40V** [comment]
The colors of the disabled pipeline are defined as constants in the method _pipeline_node_colors_ of the [pipeline_tools module of capsul](https://github.com/populse/capsul/blob/master/capsul/pipeline/pipeline_tools.py). 
We could overload this method or make a pull request to capsul after selecting more appropriate colors.

**Comment by denisri** [comment]
Sure.
We planned also to make a system to change these colors depending on the application or user settings, but of course never did...

**Comment by M40V** [comment]
https://github.com/populse/capsul/commit/fb1a5363e3253cfd9a567c09db42344eb05f52e7
