### ISSUE TITLE
MIA crashes when typing any letter in the filter field

### ISSUE THREAD

**Issue by blemasso** [populse/populse_mia#84]
**Describe the bug**
When I type any letter in the filter field MIA is crashing

**Generated error**
gin-e05-laban:populse_mia blemasso$ python3 main.py
Populse_MIA in "developer" mode
/Users/blemasso/.populse_mia/configuration.yml has been detected.
Checking the installed versions of nipype and mia_processes ...
*************************************************************
- mia use already the installed version of nipype and mia_processes (1.1.9 and 1.1.1 respectively)
Exception hooking in progress ...
Clean up before closing mia done ...
Traceback (most recent call last):
  File "/Users/blemasso/Data_non_synch/Populse/populse_mia/python/populse_mia/data_browser/data_browser.py", line 605, in search_str
    return_list = [getattr(scan, TAG_FILENAME) for scan in generator]
  File "/Users/blemasso/Data_non_synch/Populse/populse_mia/python/populse_mia/data_browser/data_browser.py", line 605, in <listcomp>
    return_list = [getattr(scan, TAG_FILENAME) for scan in generator]
  File "/Users/blemasso/.local/lib/python3.7/site-packages/populse_db/database.py", line 1510, in filter_documents
    filter_query = self.__filter_query(collection, filter_query)
  File "/Users/blemasso/.local/lib/python3.7/site-packages/populse_db/database.py", line 1483, in __filter_query
    tree = populse_db.filter.filter_parser().parse(filter)
  File "/Users/blemasso/.local/lib/python3.7/site-packages/populse_db/filter.py", line 109, in filter_parser
    _grammar_parser = Lark(filter_grammar)
  File "/Users/blemasso/.local/lib/python3.7/site-packages/lark/lark.py", line 221, in __init__
    self.parser = self._build_parser()
  File "/Users/blemasso/.local/lib/python3.7/site-packages/lark/lark.py", line 241, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "/Users/blemasso/.local/lib/python3.7/site-packages/lark/parser_frontends.py", line 141, in __init__
    self._prepare_match(lexer_conf)
  File "/Users/blemasso/.local/lib/python3.7/site-packages/lark/parser_frontends.py", line 157, in _prepare_match
    raise ValueError("Dynamic Earley doesn't support weights on terminals", t, t.priority)
ValueError: ("Dynamic Earley doesn't support weights on terminals", TerminalDef('KEYWORD_LITERAL', '(?i:(?:(?i:(?:(?i:NULL)|(?i:TRUE)))|(?i:FALSE)))'), 2)

**To Reproduce**
I open MIA, then, when I enter any letter (or number, or symbol) in the filter field, MIA crashes.
It happens with or without any project open/

**Desktop (please complete the following information):**
 - MacOs 10.14.4

**Comment by servoz** [comment]
Not sure, but this sounds like an [already opened issue in the populse_db](https://github.com/populse/populse_db/issues/33), or strongly linked with ?

**Comment by blemasso** [comment]
ok noted

**Comment by servoz** [comment]
Please, can you type in a shell (and give the return):
`python3 -m pip show lark_parser`

**Comment by blemasso** [comment]
nothing...

**Comment by servoz** [comment]
and 
`python3 -m pip list`

**Comment by blemasso** [comment]
gin-e05-laban:populse_mia blemasso$ python3 -m pip list
Package                            Version    
---------------------------------- -----------
alabaster                          0.7.12     
anaconda-client                    1.7.2      
anaconda-navigator                 1.9.7      
anaconda-project                   0.8.2      
appnope                            0.1.0      
appscript                          1.0.1      
asn1crypto                         0.24.0     
astroid                            2.2.5      
astropy                            3.1.2      
atomicwrites                       1.3.0      
attrs                              19.1.0     
Babel                              2.6.0      
backcall                           0.1.0      
backports.os                       0.1.1      
backports.shutil-get-terminal-size 1.0.0      
beautifulsoup4                     4.7.1      
bitarray                           0.8.3      
bkcharts                           0.2        
bleach                             3.1.0      
bokeh                              1.0.4      
boto                               2.49.0     
Bottleneck                         1.2.1      
capsul                             2.2.1      
certifi                            2019.3.9   
cffi                               1.12.2     
chardet                            3.0.4      
Click                              7.0        
cloudpickle                        0.8.0      
clyent                             1.2.2      
colorama                           0.4.1      
conda                              4.6.14     
conda-build                        3.17.8     
conda-verify                       3.1.1      
contextlib2                        0.5.5      
cryptography                       2.6.1      
cycler                             0.10.0     
Cython                             0.29.6     
cytoolz                            0.9.0.1    
dask                               1.1.4      
decorator                          4.4.0      
defusedxml                         0.5.0      
distributed                        1.26.0     
docutils                           0.14       
entrypoints                        0.3        
et-xmlfile                         1.0.1      
fastcache                          1.0.2      
filelock                           3.0.10     
Flask                              1.0.2      
funcsigs                           1.0.2      
future                             0.17.1     
gevent                             1.4.0      
glob2                              0.6        
gmpy2                              2.0.8      
greenlet                           0.4.15     
h5py                               2.9.0      
heapdict                           1.0.0      
html5lib                           1.0.1      
idna                               2.8        
imageio                            2.5.0      
imagesize                          1.1.0      
importlib-metadata                 0.0.0      
ipykernel                          5.1.0      
ipython                            7.4.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.4.2      
isodate                            0.6.0      
isort                              4.3.16     
itsdangerous                       1.1.0      
jdcal                              1.4        
jedi                               0.13.3     
Jinja2                             2.10       
jsonschema                         3.0.1      
jupyter                            1.0.0      
jupyter-client                     5.2.4      
jupyter-console                    6.0.0      
jupyter-core                       4.4.0      
jupyterlab                         0.35.4     
jupyterlab-server                  0.2.0      
keyring                            18.0.0     
kiwisolver                         1.0.1      
lark-parser                        0.7.1      
lazy-object-proxy                  1.3.1      
libarchive-c                       2.8        
lief                               0.9.0      
llvmlite                           0.28.0     
locket                             0.2.0      
lxml                               4.3.2      
MarkupSafe                         1.1.1      
matplotlib                         3.0.3      
mccabe                             0.6.1      
mia-processes                      1.1.1      
mistune                            0.8.4      
mkl-fft                            1.0.10     
mkl-random                         1.0.2      
more-itertools                     6.0.0      
mpmath                             1.1.0      
msgpack                            0.6.1      
multipledispatch                   0.6.0      
navigator-updater                  0.2.1      
nbconvert                          5.4.1      
nbformat                           4.4.0      
networkx                           2.2        
neurdflib                          5.0.0.post1
nibabel                            2.4.0      
nipype                             1.1.9      
nltk                               3.4        
nose                               1.3.7      
notebook                           5.7.8      
numba                              0.43.1     
numexpr                            2.6.9      
numpy                              1.16.2     
numpydoc                           0.8.0      
olefile                            0.46       
openpyxl                           2.6.1      
packaging                          19.0       
pandas                             0.24.2     
pandocfilters                      1.4.2      
parso                              0.3.4      
partd                              0.3.10     
path.py                            11.5.0     
pathlib2                           2.3.3      
patsy                              0.5.1      
pep8                               1.7.1      
pexpect                            4.6.0      
pickleshare                        0.7.5      
Pillow                             5.4.1      
pip                                19.0.3     
pkginfo                            1.5.0.1    
pluggy                             0.9.0      
ply                                3.11       
populse-db                         1.0.1      
populse-mia                        1.1.1      
prometheus-client                  0.6.0      
prompt-toolkit                     2.0.9      
prov                               1.5.3      
psutil                             5.6.1      
ptyprocess                         0.6.0      
py                                 1.8.0      
pycodestyle                        2.5.0      
pycosat                            0.6.3      
pycparser                          2.19       
pycrypto                           2.6.1      
pycurl                             7.43.0.2   
pydot                              1.4.1      
pydotplus                          2.0.2      
pyflakes                           2.1.1      
Pygments                           2.3.1      
pylint                             2.3.1      
pyodbc                             4.0.26     
pyOpenSSL                          19.0.0     
pyparsing                          2.3.1      
PyQt5                              5.12.2     
PyQt5-sip                          4.19.17    
pyrsistent                         0.14.11    
PySocks                            1.6.8      
pytest                             4.3.1      
pytest-arraydiff                   0.3        
pytest-astropy                     0.5.0      
pytest-doctestplus                 0.3.0      
pytest-openfiles                   0.3.2      
pytest-remotedata                  0.3.1      
python-dateutil                    2.8.0      
pytz                               2018.9     
PyWavelets                         1.0.2      
PyYAML                             5.1        
pyzmq                              18.0.0     
QtAwesome                          0.5.7      
qtconsole                          4.4.3      
QtPy                               1.7.0      
rdflib                             4.2.2      
requests                           2.21.0     
rope                               0.12.0     
ruamel-yaml                        0.15.46    
scikit-image                       0.14.2     
scikit-learn                       0.20.3     
scipy                              1.2.1      
seaborn                            0.9.0      
Send2Trash                         1.5.0      
setuptools                         40.8.0     
simplegeneric                      0.8.1      
simplejson                         3.16.0     
singledispatch                     3.4.0.3    
sip                                4.19.8     
six                                1.12.0     
snakeviz                           2.0.0      
snowballstemmer                    1.2.1      
soma-base                          4.6.4      
soma-workflow                      3.0.0      
sortedcollections                  1.1.2      
sortedcontainers                   2.1.0      
soupsieve                          1.8        
Sphinx                             1.8.5      
sphinxcontrib-websupport           1.1.0      
spyder                             3.3.3      
spyder-kernels                     0.4.2      
SQLAlchemy                         1.3.1      
statsmodels                        0.9.0      
sympy                              1.3        
tables                             3.5.1      
tblib                              1.3.2      
terminado                          0.8.1      
testpath                           0.4.2      
toolz                              0.9.0      
tornado                            6.0.2      
tqdm                               4.31.1     
traitlets                          4.3.2      
traits                             5.1.1      
unicodecsv                         0.14.1     
urllib3                            1.24.1     
wcwidth                            0.1.7      
webencodings                       0.5.1      
Werkzeug                           0.14.1     
wheel                              0.33.1     
widgetsnbextension                 3.4.2      
wrapt                              1.11.1     
wurlitzer                          1.0.2      
xlrd                               1.2.0      
XlsxWriter                         1.1.5      
xlwings                            0.15.4     
xlwt                               1.3.0      
zict                               0.1.4      
zipp                               0.3.3

**Comment by servoz** [comment]
Please, run in a terminal:
`python3 -m pip show lark-parser`

**Comment by blemasso** [comment]
(base) gin-e05-laban:~ blemasso$ python3 -m pip show lark-parser
Name: lark-parser
Version: 0.7.1
Summary: a modern parsing library
Home-page: https://github.com/erezsh/lark
Author: Erez Shinan
Author-email: erezshin@gmail.com
License: MIT
Location: /Users/blemasso/.local/lib/python3.7/site-packages
Requires: 
Required-by: populse-mia, populse-db

**Comment by servoz** [comment]
Please, run in a terminal:
`python3 -m pip install -I "lark-parser<0.7.0 --user"`
Then:
`python3 -c "import lark; print(lark.__version__)"`

**Comment by servoz** [comment]
This is the minimal hack, before really fix the already opened issue in the populse_db. Let us know if it is ok for you now

**Comment by blemasso** [comment]
I downgraded lark-parser from 0.7.1 to 0.6.7 on my Conda environment
>> python3 -c "import lark; print(lark.__version__)"
>> 0.6.7
And now it is working!
