### ISSUE TITLE
File>Import does nothing

### ISSUE THREAD

**Issue by adelphin** [populse/populse_mia#85]
Using populse_mia 1.1.1 with python 3.7 on an ubuntu 18.04, the File>Import does nothing, as well as Ctrl+I.
The following message appears in my python console:
> Error: Unable to access jarfile

This message appears every time I click on File>Import or press Ctrl+I.
However, the big green + in the bottom left corner does open a window allowing me to import data.

**Comment by M40V** [comment]
I think the path to MRIFileManager is not correctly defined.
You can update it in File > MIA preferences, then select the path to "MRIManager.jar", for Ubuntu it should be "_~/.populse_mia/mri_conv/MRIFileManager/MRIManager.jar_".

**Comment by adelphin** [comment]
Problem quickly solved indeed, thanks!

**Comment by adelphin** [comment]
A nice enhancement could be to have an explicit popup indicating which path is faulty.
e.g. in my case a popup specifying :
> Could not open MRIFileManager, please check the path to MRIManager.jar in preferences

**Comment by servoz** [comment]
OK, we leave this ticket open to don't forget to do it ASAP
