### ISSUE TITLE
third-party software components in MIA

### ISSUE THREAD

**Issue by clemacq** [populse/populse_mia#86]
**Expected behavior**
Being able to load third-party software components other than SPM such as ANTS, FSL, ...

**Actual behavior**
In MIA preferences, it is not possible to specify the path to software other than SPM and then a MIA pipeline cannot use algorithms coming from nipype.interfaces.ants, nipype.interfaces.fsl, etc...

**Comment by servoz** [comment]
absolutely agree ... we know... and it's to be done ASAP... like many things......

**Comment by servoz** [comment]
FSL configuration has been added to the Mia preferences. We currently do not have enough developers in Populse to code the configuration of all the existing softwares in the Mia preferences (and capsul engine). It may be considered to do when a software usage need is highlighted.
