### ISSUE TITLE
[continuous integration] Implement unitary tests to improve code coverage

### ISSUE THREAD

**Issue by M40V** [populse/populse_mia#87]
We must develop unitary tests to improve code coverage, increase reliability and quickly detect bugs when new functionalities are implemented.

There is list of all the tests we should implement or improve on [Trello](https://trello.com/invite/b/KR1AJsQN/e62f8877e6e7b91995c13f72e03b582a/populsemia), you can check the current code coverage on [codecov.io](https://codecov.io/gh/populse/populse_mia/tree/master/python/populse_mia) to identify the parts which are not yet tested.

**Comment by servoz** [comment]
It would be necessary to increase the code coverage by adding new tests to be performed.

It would also be necessary to uncomment some existing tests, which have certainly been commented on because they don't work (or no longer work).

**Comment by servoz** [comment]
Increasing code coverage will always be an important goal.
However with the recent work of @patafana on UTs (going from 60 to 85 coverage rate) I think this ticket can be closed for now.

**Comment by LStruber** [comment]
Well done @patafana !
