### ISSUE TITLE
Developer installation documentation needs improvement

### ISSUE THREAD

**Issue by BlancaNietoPetinal** [populse/populse_mia#90]
**Describe the bug**
The developer installation documentation at [https://populse.github.io/populse_mia/html/installation/developer_installation.html](https://populse.github.io/populse_mia/html/installation/developer_installation.html) states to install using:
```
sudo python3 setup.py install
```

However, **servoz** says to not use sudo to install mia. When installing without sudo, the installation fails because it tries to write into /usr...
It is not obvious how to specify a different install path. For example:

```
python3 setup.py --install-dir /home/nietob/.local/lib/python3.6/site-packages install
```
Fails because the option --install-dir is not known.

**Generated error**
```
modules found:  ['populse_mia', 'populse_mia.utils', 'populse_mia.user_interface', 'populse_mia.sources_images', 'populse_mia.#image_viewer', 'populse_mia.data_manager', 'populse_mia.user_interface.data_browser', 'populse_mia.user_interface.pipeline_manager']
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/test-easy-install-29832.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

**To Reproduce**
1. Start from a computer without populse_mia
2. git clone ...
3. cd populse_mia
4. sudo python3 setup.py install

**Expected behavior**
Insallation should _Just Work_(TM)

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Populse_MIA version github version as of today

**Comment by servoz** [comment]
Yes it is true that we have to improve the documentation for populse_mia.

It is also true that using sudo with pip or setuptools can be view as criminal:-)))

We will improve documentation ASAP.
For now try:
`python3 setup.py install --user`

**Comment by BlancaNietoPetinal** [comment]
Perfect!
```
python3 setup.py install --user
```
works!

**Comment by servoz** [comment]
[Cool!!!](https://www.youtube.com/watch?v=tSWf_yIV-d4).
We leave this ticket open, so that we don't forget to work ASAP on the documentation, that needs a real clean up ...

**Comment by JanWP** [comment]
For information, here are my notes on how to install MIA in a virtual environment from the sources, with populse_db, capsul and mia_processes installed from sources as well. The different steps are noted such that they are independent - obviously the `workon` command is only necessary once in a terminal session if several of the steps are performed. All the code will reside in a directory called `populse_mia_dir`, and the virtual environment in this example is `populse_mia_env`. Both can be adapted at will (and possibly have the same name if desired).

**Prepare virtual environment and working directory**
<pre>
mkvirtualenv --no-site-packages --python=/usr/bin/python3 populse_mia_env
mkdir ~/<i>my_code_directory</i>/populse_mia_dir
</pre>

**Install populse_db**
<pre>
cd ~/<i>my_code_directory</i>/populse_mia_dir
git clone git@github.com:populse/populse_db.git
cd populse_db
workon populse_mia_env
python3 setup.py install --prefix ~/.virtualenvs/populse_mia_env
</pre>

**Install capsul**
<pre>
cd ~/<i>my_code_directory</i>/populse_mia_dir
git clone git@github.com:populse/capsul.git capsul
cd capsul
workon populse_mia_env
python3 setup.py install --prefix ~/.virtualenvs/populse_mia_env
</pre>

**Install mia_processes**
<pre>
cd ~/<i>my_code_directory</i>/populse_mia_dir
git clone git@github.com:populse/mia_processes.git mia_processes
cd mia_processes
workon populse_mia_env
python3 setup.py install --prefix ~/.virtualenvs/populse_mia_env
</pre>

**Install populse_mia**
<pre>
cd ~/<i>my_code_directory</i>/populse_mia_dir
git clone git@github.com:populse/populse_mia.git populse_mia
cd populse_mia
workon populse_mia_env
python3 setup.py install --prefix ~/.virtualenvs/populse_mia_env
</pre>

**Run populse_mia**
<pre>
cd ~/<i>my_code_directory</i>/populse_mia_dir/populse_mia
workon populse_mia_env
python3 python/populse_mia/main.py
</pre>

**Comment by servoz** [comment]
Great! This will be valuable when we finally start redesigning the documentation!
Tanks @JanWP

**Comment by servoz** [comment]
A special effort in this direction has now been made.
