### ISSUE TITLE
Mia crashes when running a pipeline and 'use SPM' is not checked 

### ISSUE THREAD

**Issue by BlancaNietoPetinal** [populse/populse_mia#93]
**Describe the bug**
MIA tries to run pipelines even if Matlab and SPM are not configured in the preferences. However, when doing so, MIA crashes.

An unconfigured SPM in the preferences can occur, when unchecking the "Use Matlab" checkbox after enabling SPM. In this case, the "Use SPM" checkbox is disabled, and not re-enabled automatically if Matlab is enabled again.

**Generated error**
```
________________________________________________________________________________
[Process] Calling nipype.interfaces.spm.preprocess.Smooth...
nipype.interfaces.spm.preprocess.Smooth(output_directory=/home/nietob/Data/mia/projects/test/scripts, synchronize=0, fwhm=[3.0, 3.0, 3.0], in_files=['/home/nietob/Data/mia/projects/test/data/raw_data/MAP-VS-704-599566309-2019-04-05_09-39-09-00-3D_pCASL_singleshot-3D_pCASL_singleshot-.nii'], matlab_cmd=/usr/local/MATLAB/R2019a/bin/matlab, mfile=True, out_prefix=s, use_mcr=False, use_v8struct=True)

Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/home/nietob/Code/Populse_mia/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1465, in run
    study_config.run(pipeline, verbose=1)
  File "/home/nietob/.local/lib/python3.6/site-packages/capsul/study_config/study_config.py", line 414, in run
    verbose)
  File "/home/nietob/.local/lib/python3.6/site-packages/capsul/study_config/study_config.py", line 471, in _run
    **kwargs)
  File "/home/nietob/.local/lib/python3.6/site-packages/capsul/study_config/run.py", line 102, in run_process
    returncode = process_instance._run_process()
  File "/home/nietob/.local/lib/python3.6/site-packages/capsul/process/process.py", line 1240, in _run_process
    results = self._nipype_interface.run()
  File "/home/nietob/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/home/nietob/.local/lib/python3.6/site-packages/nipype/interfaces/spm/base.py", line 376, in _run_interface
    results = self.mlab.run()
  File "/home/nietob/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/home/nietob/.local/lib/python3.6/site-packages/nipype/interfaces/matlab.py", line 170, in _run_interface
    self.raise_exception(runtime)
  File "/home/nietob/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
/usr/local/MATLAB/R2019a/bin/matlab -nodesktop -nosplash -singleCompThread -r "addpath('/home/nietob/Data/mia/projects/test/scripts');pyscript_smooth;exit"
Standard output:

                                                                              < M A T L A B (R) >
                                                                    Copyright 1984-2019 The MathWorks, Inc.
                                                               R2019a Update 2 (9.6.0.1114505) 64-bit (glnxa64)
                                                                                  May 1, 2019

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
The Window Command log is currently saved in ~/Documents/MATLAB/diaryWindowCommand file. Purge sometimes the diaryWindowCommand file in MATLAB directory.
- diary off: suspends the diary.
- diary on: resumes diary mode.

By default at start up a debugging option is launched producing a breakpoint and pause execution if a run-time error occurs.
- For stop this option: dbclear all.
- For start this option: dbstop if error.
- For known the current option: dbstatus.
Executing pyscript_smooth at 18-Jun-2019 12:15:32:
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.6.0.1114505 (R2019a) Update 2
MATLAB License Number: 100877
Operating System: Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64
Java Version: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.6         (R2019a)
Deep Learning Toolbox                                 Version 12.1        (R2019a)
Image Processing Toolbox                              Version 10.4        (R2019a)
MATLAB Compiler                                       Version 7.0.1       (R2019a)
MATLAB Compiler SDK                                   Version 6.6.1       (R2019a)
Optimization Toolbox                                  Version 8.3         (R2019a)
Parallel Computing Toolbox                            Version 7.0         (R2019a)
Signal Processing Toolbox                             Version 8.2         (R2019a)
Statistical Parametric Mapping                        Version 7487        (SPM12) 
Statistics and Machine Learning Toolbox               Version 11.5        (R2019a)

Standard error:
MATLAB code threw an exception:
Cannot CD to /home/nietob/Data/mia/projects/test/scripts/<undefined> (Name is nonexistent or not a directory).
File:/home/nietob/Data/mia/projects/test/scripts/pyscript_smooth.m
Name:pyscript_smooth
Line:4
Return code: 0
QObject::~QObject: Timers cannot be stopped from another thread
Segmentation fault (core dumped)
```
Notice that the option "paths=['/home/nietob/spm12']" is missing from the call to nipype.interfaces.spm.preprocess.Smooth.

**To Reproduce**
1. Open a project
2. In Preferences > Pipeline uncheck "Use Matlab" and check it again. The "Use SPM" checkbox got disabled in the process.
3. Click on "OK". 
4. Configure a simple pipeline with an SPM module like smooth. Initialize and run it.
5. MIA crashes.

**Expected behavior**
MIA should open an error dialog, informing the user that SPM and/or Matlab needs to be enabled in the preferences. 
In the preferences dialog, maybe SPM should not be automatically disabled when disabling Matlab (or it should be automatically re-enabled when it was automatically disabled before).

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu 18.04, Plasma desktop
 - Populse_MIA version 1.2.1

**Comment by M40V** [comment]
This functionnality will be fully incorporated when we will shift to the capsul engine. Processes will have requirements and it will be mandatory to have these requirements enabled to initialize and run the pipeline.

Currently we are checking during the initialization if the processes are from nipype (pipeline_manager_tab.py L745), we could add a condition to stop the initialization if SPM is not correctly defined in the config.yml. It will resolve this issue before the shift to the capsul engine.

**Comment by servoz** [comment]
It is very desirable that the mia version in production never crashes.

We don't know yet when the capsul_engine will definitely be used in mia and I confess that the scope of action stay a little bit confuse (the capsul engine is still in the process of being written by the capsul team).

So, I think we need to make a little change ASAP to fix this possibility of a crash of mia

**Comment by M40V** [comment]
The verification will occur during the initialization of the pipeline. 
This verification can occur at different points, depending on whether MIA should always run with SPM or if SPM should be configured only when specific processes require it. 
We can then inform the user that the pipeline wasn't initialized with the statusbar and an alert.
Currently nothing forbids an user to run a pipeline, even if it wasn't initialized correctly, should we add a boolean to avoid  these behaviors ?

**Comment by servoz** [comment]
As we have seen, it may be considered to merge the initialisation and the launch of the pipeline run (currently, users must click on an Initialise button and a Run button), which would solve the problem of a launch without having initialised. On the other hand, it might be very desirable for the user to know before the actual start of all processes, if everything goes well (which can be crucial in the case of iteration, that can take a long time).  A complete initialisation of the entire pipeline through all iterated tags could therefore be a real improvement.

**Comment by M40V** [comment]
There is two parts to this issue. The first part is about the configuration of Matlab and SPM in Mia preferences and the second part is during the initialization if SPM or Matlab are used by the brick (check if Nipype is used or if user bricks use spm).

**Comment by M40V** [comment]
The [commit](https://github.com/populse/populse_mia/tree/e5d3d81ac9d2233eabfe0854cecee727b641cb9f) updates the MIA preferences pop so that Matlab will always be required with SPM and Matlab standalone for SPM standalone.

We still need to add a check during the initialization of a pipeline to see if SPM and Matlab are required and cancel the initialization if they're not configured.

**Comment by servoz** [comment]
Commit e5d3d81a are still in your branch, isn’t it ? Not found in master from the link above.

**Comment by M40V** [comment]
Yes, I wanted to finish the method that checks if nipype.interfaces.spm is a dependency. I tried to use importlib and sys.modules to identify the dependencies of a package but for now I was not able to isolate the dependencies of a package.

We could develop a method to verify the imports by reading the file (like check_imports), but it's not very elegant and far from foolproof, I think it's better to explore others Python solutions to check dependencies. I merged my current progress on master.

**Comment by M40V** [comment]
[ModuleFinder](https://docs.python.org/fr/3/library/modulefinder.html) does everything we need but it has some issues with [jinja2](https://stackoverflow.com/questions/43163201/pyinstaller-syntax-error-yield-inside-async-function-python-3-5-1). 
The method used to find dependencies fails if jinja2 version is above 2.8.1, but it only fails once, by running this method twice we can check dependencies without restricting populse_mia dependencies.

We can either set jinja2==2.8.1 in info.py , install the dev version of Pyinstaller or run ModuleFinder.run_script() twice while catching the error (not the cleanest option).
I will commit the new method today and we'll just have to modify some lines depending on the option we choose.

**Comment by M40V** [comment]
ModuleFinder takes a lot of time to run, the initialization is slower than before with this [commit](https://github.com/populse/populse_mia/commit/19e2875a4a1dbd3f80c56ce986568356408d317e).

**Comment by JanWP** [comment]
Here, when following the steps outlined in the issue report, MIA still tries to call SPM and stalls or crashes.

**Comment by M40V** [comment]
I made a new [commit](https://github.com/populse/populse_mia/commit/0fbd2ba55a5bd0514a32245595ca742593e3eacc) that disable these checks when in developer mode. We'll need to discuss the best way to have a strong code without losing too much efficiency.

**Comment by M40V** [comment]
The status_label doesn't update when the configuration of Matlab&SPM is checked in the MIA preferences popup.

**Comment by M40V** [comment]
By adding a QCoreApplication.processEvents() just after, the status_label update correctly.

**Comment by servoz** [comment]
Have you ever pushed this change ?

**Comment by servoz** [comment]
I guess now mia preference can check the spm path when entering a new one (independently of the default path  already defined by the user in matlab).

**Comment by servoz** [comment]
- In pipeline mia preference it seems that when the path already exists, the check change is not saved !

**Comment by M40V** [comment]
https://github.com/populse/populse_mia/commit/58c49d70ff9929a5811897ee568a183e0b2483ff

**Comment by servoz** [comment]
If the configuration at opening is Use Matlab. If we check Use Matlab standalone then click on OK the configuration is not changed (if you still open File > Mia preferences > Pipeline, it is yet  Use Matlab that is checked)

**Comment by M40V** [comment]
It's fixed. https://github.com/populse/populse_mia/commit/7c9a66901c4d5a4f17001e66c64308940f6406c5

**Comment by servoz** [comment]
Currently, in the config.yml file, the use_matlab parameter has a double signification.

First it indicates whether matlab (in the Runtime case, that we call Matlab standalone, or in the license case, that we call only Matlab) is chosen in the mia configuration.

Secondly, it indicates whether Matlab (in the non-standalone sense) is chosen. 
In order to know if we are using Matlab or Matlab standalone it is necessary to know the combination of use_matlab and use_matlab_standalone parameters.

Indeed, if we want to use Matlab, we must define use_matlab=True and use_matlab_standalone=False.

If we want to use Matlab standalone, you must define use_matlab=True and use_matlab_standalone=True.

This leads 2 states of different configurations giving the same result.
Example: no use of Matlab or Matlab standalone corresponds to two states:
- use_matlab=False and use_matlab_standalone=True
- as well as matlab=False and use_matlab_standalone=False.

I have no certainty about the side effects that could result from this situation.

Another way of working would be to have only:
-  use_matlab=True and use_matlab_standalone=False (Matlab)
- or matlab=False and use_matlab_standalone=True (Matlab standalone)
- or use_matlab=False and use_matlab_standalone=False (neither one nor the other)
- the other situations being prohibited.

Since we have not yet detected any side effects and changing the way it works would require changing more or less the codes, I propose to do not change the codes.

Let's hope we don't discover side effects later!

**Comment by JanWP** [comment]
There is another option: Keep only the "use_matlab" variable and let it have non-boolean values.
For example: use_matlab=None (or ""), use_matlab="standalone", use_matlab="interpreter"
This would still allow syntax like
```python
if use_matlab:
   # do stuff
```

In addition, this could later be further amended if the need arises:
use_matlab="R2019a interpreter"

**Comment by servoz** [comment]
It is a very good idea to keep in mind if we decide to change the code later.
Currently, we have not detected any side effects and because we have so many other important issues to deal with, we have decided as long as the code remains robust on this point to not change it)
