### ISSUE TITLE
Virtual entries generated in the data browser by pipeline initialization are not removed when obsolete

### ISSUE THREAD

**Issue by BlancaNietoPetinal** [populse/populse_mia#94]
**Describe the bug**
Initializing a pipeline generates virtual entries in the Data Browser, corresponding to the output the pipeline would produce if it was run. If the user modifies the pipeline before running it and initializes it again, additional entries are generated and the now obsolete entries are not removed.

**Generated error**
None

**To Reproduce**
1. Open a project
2. Create a new pipeline with just a "smooth" brick. Export the in_files, fwhm and out_prefix plugs.
3. Specify an input file and initialize the pipeline.
4. Now modify the output prefix and initialize the pipeline again.
5. Now modify the fwhm and initialize the pipeline again.
6. Run the pipeline.
7. Look at the Data Browser. There are two entries for the smoothed file, and the second one has two Bricks associated with it - with different fwhms.

**Expected behavior**
When initializing a pipeline, old virtual entries that do not correspond to actual images or to the current pipeline configuration should be removed from the Data Browser. In this case, only one entry with one brick (the one that was run) should remain.

**Screenshots**
![Screenshot_20190618_125731](https://user-images.githubusercontent.com/26384451/59677111-64605680-91c9-11e9-9989-2f469de53a0f.png)

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 18.04, Plasma desktop
 - Populse_MIA version 1.2.1

**Comment by servoz** [comment]
Sorry @BlancaNietoPetinal for the delay, I have seen your post but I have not yet found the time to do some tests in order to try a more or less smart answer...Your ticket is very important and I come back ASAP !
