### ISSUE TITLE
Remove all the Gtk-Message and Gtk-WARNING returns, during the use of mia.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#95]
ex:
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`
or
`(python3:8860): Gtk-WARNING **: Failed to measure available space: The specified location is not supported`
etc .

**Comment by M40V** [comment]
We can observe this issue when using the "browse" function in "MIA preferences" for "project folder". I do not observe these warnings on my station but they are present on @servoz one.

**Comment by servoz** [comment]
Just tested today:

- File > MIA preferences : Browse buttons gives:
  - With 5.3.11-300.fc31.x86_64 OS, Python 3.7.5, Qt version: 5.13.2, SIP version: 5.0.0, PyQt version: 5.13.2:
(python3:30923): Gtk-WARNING **: 17:11:01.699: Failed to measure available space: The specified location is not supported
(python3:30923): Gtk-WARNING **: 17:11:01.699: Failed to measure available space: The specified location is not supported


- File > Save project as:
  - With 5.3.11-300.fc31.x86_64 OS, Python 3.7.5, Qt version: 5.13.2, SIP version: 5.0.0, PyQt version: 5.13.2:
(python3:31152): Gtk-WARNING **: 17:13:44.660: Failed to measure available space: The specified location is not supported
(python3:31152): Gtk-WARNING **: 17:13:44.660: Failed to measure available space: The specified location is not supported

- to continue ...

**Comment by M40V** [comment]
With Python version 3.5.2, SIP version 4.19.8,  and PyQt version 5.11.3 it works without any warning. I'll update my configuration to see if I can reproduce these warnings.

**Comment by servoz** [comment]
Not observed with Precision 7530 laptop:
- 5.6.6-200.fc31.x86_64
- PyQt5 5.14.2
- PyQt5-sip 12.7.2
- sip 5.2.0

I do not understand this problem. I close this ticket ... to open again if necessary ...
