### ISSUE TITLE
Graphical issue with the avanced search

### ISSUE THREAD

**Issue by M40V** [populse/populse_mia#99]
**Describe the bug**
When we use the advanced search in a project, switch tabs then come back to the databrowser tab, the "plus" and "minus" button of the advanced search are resized or misplaced.

**To Reproduce**
1. Open a project or load documents
2. Click on advanced search
3. Define a filter with at least one result and launch the advanced search
4. Switch tabs.
5. Go back to the databrowser tab, you'll see the graphical issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/14822018/60272874-3c71a100-98f5-11e9-9df1-c3a194918670.png)

**Comment by servoz** [comment]
I observe the same thing in linux or macOS !

**Comment by M40V** [comment]
In the _remove_row_ method, the rows of the advanced search, the Qt objects were not deleted. 
This bug was fixed with this [commit](https://github.com/populse/populse_mia/commit/1ae9a58eef7fd1678566b7e00805234f6bf73838).
It caused some visual issues when adding and removing rows. This doesn't fix the graphical issue we have after switching tabs but it could be a similar problem of not deleting objects.
